//! Observability: counters and collected notifications from a run.

use fanos_diakrisis::Verdict;
use fanos_runtime::{Notification, Triple};

/// Aggregate counters over a simulation run. Deterministic for a given `(seed, scenario)`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Metrics {
    /// Frames handed to the transport.
    pub frames_sent: u64,
    /// Frames delivered to a live node.
    pub frames_delivered: u64,
    /// Frames dropped (loss, partition, or crashed destination).
    pub frames_dropped: u64,
    /// Timers fired.
    pub timers_fired: u64,
    /// Application payloads delivered.
    pub payloads_delivered: u64,
    /// Peer-down observations reported by nodes.
    pub peer_downs: u64,
    /// Self-healing reroutes installed (down node → co-linear survivor).
    pub reroutes: u64,
    /// Lost shards regenerated by peeling.
    pub repairs: u64,
    /// Byzantine members locally quarantined.
    pub quarantines: u64,
    /// Residues escalated to the parent cell.
    pub escalations: u64,
    /// Pre-emptive decouple actions (cascade early-warning).
    pub decouples: u64,
    /// DHT `Put` acknowledgements observed.
    pub stores: u64,
    /// DHT `Get` completions that returned a value.
    pub retrieval_hits: u64,
    /// DHT `Get` completions that found nothing.
    pub retrieval_misses: u64,
    /// Values accounted **permanently lost** — a held key became unrecoverable past the erasure tolerance
    /// (audit R-C3): durable loss made visible, distinct from a transient/never-stored miss.
    pub data_losses: u64,
    /// Mandatory self-observations emitted (one `CoherenceFrame` per node per diagnosis).
    pub observations: u64,
}

/// A notification observed from a node, tagged with the observer's coordinate.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Observed {
    /// The node that emitted the notification.
    pub node: Triple,
    /// The notification.
    pub note: Notification,
}

/// The collected output of a run: counters plus every application notification, in order.
#[derive(Clone, Debug, Default)]
pub struct Report {
    /// Aggregate counters.
    pub metrics: Metrics,
    /// Every notification emitted, in causal (event) order.
    pub notifications: Vec<Observed>,
}

impl Report {
    /// All diagnosis verdicts observed, in order (double-ended for tail inspection).
    pub fn verdicts(&self) -> impl DoubleEndedIterator<Item = (Triple, &Verdict)> {
        self.notifications.iter().filter_map(|o| match &o.note {
            Notification::Verdict(v) => Some((o.node, v)),
            _ => None,
        })
    }

    /// Whether any node reached the given verdict.
    #[must_use]
    pub fn any_verdict(&self, wanted: &Verdict) -> bool {
        self.verdicts().any(|(_, v)| v == wanted)
    }

    /// The application payloads delivered, as `(receiver, sender, bytes)`.
    pub fn deliveries(&self) -> impl Iterator<Item = (Triple, Triple, &[u8])> {
        self.notifications.iter().filter_map(|o| match &o.note {
            Notification::Delivered { from, payload } => Some((o.node, *from, payload.as_slice())),
            _ => None,
        })
    }

    /// The self-healing reroutes installed, as `(observer, around, via)`.
    pub fn reroutes(&self) -> impl Iterator<Item = (Triple, Triple, Triple)> + '_ {
        self.notifications.iter().filter_map(|o| match &o.note {
            Notification::Rerouted { around, via } => Some((o.node, *around, *via)),
            _ => None,
        })
    }

    /// Whether any node repaired the given (down) coordinate's shard.
    #[must_use]
    pub fn any_repaired(&self, coord: Triple) -> bool {
        self.notifications
            .iter()
            .any(|o| matches!(&o.note, Notification::Repaired(c) if *c == coord))
    }

    /// Whether any node escalated (handed residue to the parent cell).
    #[must_use]
    pub fn any_escalated(&self) -> bool {
        self.notifications
            .iter()
            .any(|o| matches!(&o.note, Notification::Escalated(_)))
    }

    /// The DHT retrievals observed, as `(observer, key digest, value)`.
    pub fn retrievals(&self) -> impl Iterator<Item = (Triple, [u8; 32], Option<&[u8]>)> {
        self.notifications.iter().filter_map(|o| match &o.note {
            Notification::Retrieved { key, value } => Some((o.node, *key, value.as_deref())),
            _ => None,
        })
    }

    /// The nodes whose behavioural homeostat shed correlation (fired `Decouple`), in causal order — the
    /// live coherence self-model acting on measured over-coupling (`docs/ddos-homeostasis.md`).
    pub fn decouples(&self) -> impl Iterator<Item = Triple> + '_ {
        self.notifications.iter().filter_map(|o| match &o.note {
            Notification::Decoupled => Some(o.node),
            _ => None,
        })
    }

    /// Whether any node shed correlation under behavioural over-coupling.
    #[must_use]
    pub fn any_decoupled(&self) -> bool {
        self.notifications
            .iter()
            .any(|o| matches!(&o.note, Notification::Decoupled))
    }
}
