//! The **DIAKRISIS self-healing reflex** — the node's verified reflex layer, factored out of `OverlayNode`.
//!
//! Split from `overlay.rs` (audit #125 decompose, task 7a): the behavioural coherence self-model, the over-coupling
//! homeostat, and the crash/Byzantine healing state (reroute / repair / quarantine) with the live polar
//! cross-attestation it diagnoses from. `OverlayNode` keeps the *liveness sensing* — the peer substrate,
//! `coord_alive`/`cell_liveness`/`health_view`, the corroboration cache — and hands this module a **sensed** cell
//! snapshot; everything the reflex then does with that snapshot lives here.
//!
//! Deliberately not generic over `F`: the state is all concrete, and the few methods needing the cell's
//! index-addressed geometry take `<F>` per call.

use crate::overlay::{
    BEHAVIOR_WINDOW, Config, DECOUPLE_DECAY, DECOUPLE_DWELL, DECOUPLE_MAX, DECOUPLE_STEP, ENDPOINT_MIN_STALE,
    ENDPOINT_WINDOW, PARTITION_DWELL, QUARANTINE_TTL, polar_gap_from_liveness,
};
use crate::ports::{Duration, Effect, Instant, Notification};

use alloc::collections::{BTreeMap, BTreeSet, VecDeque};
use alloc::vec::Vec;

use fanos_diakrisis::coherence::phi_equicorrelated;
use fanos_diakrisis::monitor::BehaviorMonitor;
use fanos_diakrisis::partition;
use fanos_diakrisis::polar;
use fanos_core::LiveDifficulty;
use fanos_diakrisis::regeneration;
use fanos_diakrisis::stability::{self, AdmissionController, inferred_disturbance};
use fanos_diakrisis::{BandControl, HealingAction, Homeostat, Observation, diagnose, plan_healing};
use fanos_field::Field;
use fanos_geometry::{Point, Triple};
use fanos_primitives::Epoch;
use fanos_telemetry::SelfObserver;

/// The DIAKRISIS self-healing reflex factored out of [`OverlayNode`] (audit #125 decompose): the node's
/// **verified reflex layer** (see [[synarc-node-architecture]]) — behavioural coherence self-model, the
/// over-coupling homeostat, and the crash/Byzantine healing state (reroute / repair / quarantine) with the
/// live polar cross-attestation it diagnoses from. The facade owns the *liveness sensing* (the `peers`
/// substrate + `coord_alive`/`cell_liveness`/`health_view` + the `witnessed` corroboration cache) and
/// hands this a **sensed** cell snapshot (`self_index, degraded, alive_count`); this owns everything the
/// reflex then does with it. Not generic over `F`: its state is all concrete, and the few methods that
/// need the cell's index-addressed geometry take `<F>` per call.
pub(crate) struct Healer {
    /// Live polar cross-attestation (spec §6.4, §6.2): the freshest `DiagAttest` report gossiped by each
    /// OTHER cell member — its own honest reading of the 3 channel rates it mediates (`polar::polar_class`),
    /// and when it arrived. [`attested_pairwise_rates`](Healer::attested_pairwise_rates) assembles these
    /// (falling back to this node's own reading for any member it hasn't freshly heard from) into the
    /// `Observation.pairwise_rates` matrix `diagnose` feeds the 14 free polar sum-rule alarms. An honest
    /// report's 3 values always agree (`polar::mediator_attestation`); an equivocating member's disagree
    /// internally, and `polar::violated_classes` then localizes exactly it.
    attested: BTreeMap<Triple, ([f64; 3], Instant)>,
    /// Self-healing routing state: to reach the (down) key coordinate, contact the value coordinate — the
    /// co-linear survivor from the projective LRC reroute (spec §L4).
    reroute: BTreeMap<Triple, Triple>,
    /// Nodes whose shard this cell has regenerated by peeling (spec §6.3), for observability.
    repaired: BTreeSet<Triple>,
    /// Members locally distrusted after a polar-rule violation (spec §6.2); their frames are dropped
    /// pending parental re-provisioning.
    pub(crate) quarantined: BTreeMap<Triple, Instant>,
    /// Mandatory per-node self-observation (`fanos_telemetry`): every diagnosis folds the cell's health
    /// into a `CoherenceFrame` and records it into bounded local history. Not optional — the reflexive loop
    /// cannot diagnose without observing (docs/design-telemetry.md).
    observer: SelfObserver,
    /// The behavioural coherence monitor: a bounded window of per-node relay activity, read as the cell's
    /// real `Γ_net` so the [`Homeostat`] runs on *measured* correlation, not the liveness proxy (base cell).
    monitor: BehaviorMonitor,
    /// The coherence homeostat this node runs on its behavioural self-model — the sense→act seam, with the
    /// monitor sensing and `diagnose` actuating its band-keeping decision.
    homeostat: Homeostat,
    /// The DDoS admission-price controller (T-104): raises the cost of joining this node as its own measured
    /// stress rises, and releases it at the cell's recovery constant. See `fanos_diakrisis::stability`.
    admission: AdmissionController,
    /// The previous window's `(purity, timestamp)`, so the disturbance can be inferred from the *rate* the
    /// purity is moving rather than from its level. The level only moves after damage; the rate carries an
    /// attack on the first window, which is the difference between a controller that saves a cell and one that
    /// watches it die (measured — `stability::the_admission_law_saves_a_cell_that_would_otherwise_die`).
    last_purity: Option<(f64, u64)>,
    /// Where the controller's decision is published for the admission gate to read. `None` when this node runs
    /// no proof-of-work admission, in which case there is no price to move.
    live_difficulty: Option<LiveDifficulty>,
    /// The operator's configured floor, which the controller may raise above but never go under.
    admission_floor: u32,
    /// The epoch this cell was last observed in, and the stability radius it held entering it — the two
    /// readings the cost of an epoch advance is measured from. See [`epoch_floor`](Self::epoch_floor).
    last_epoch: Option<(u64, f64)>,
    /// The most recent `(stability radius, spectral gap)` — the two per-window inputs to the epoch floor.
    latest: Option<(f64, f64)>,
    /// The stress this cell last measured — the input every control law here shares.
    ///
    /// Kept because two laws now read it at different moments: the admission price is set inside the
    /// observation that computes it, while a read's fan-out is decided whenever a `Get` arrives, which is not
    /// synchronised to anything.
    last_stress: f64,
    /// The epoch whose floor has already been reported, so each advance is reported exactly once.
    ///
    /// An epoch rather than a flag: the question is "have I told anyone about *this* advance", and the epoch
    /// answers it directly while a boolean only records that something happened.
    reported_epoch: Option<u64>,
    /// How long one observation window lasts, in seconds, measured from consecutive observations.
    ///
    /// The **unit bridge**, and it is load-bearing. The polar gap `Δ` is a count of corroborated-alive points
    /// per Fano line (a healthy cell gives `Δ = 2`), so it is *dimensionless* and `τ = 1/Δ` is a relaxation
    /// time in master-equation steps, not in seconds. One step is one observation window, so seconds only
    /// appear by multiplying through by this. Reporting `1/Δ` as a wall-clock time would have called half a
    /// step half a second.
    window_seconds: Option<f64>,
    /// The headroom the most recent epoch advance was measured to consume, and the shortest period that cost
    /// makes sustainable. `None` until a first advance has been observed — a floor derived from no measurement
    /// would be a guess wearing a derivation.
    epoch_cost: Option<f64>,
    /// Per-peer **data-relay** activity (`Route` frames) accumulated since the last behavioural sample —
    /// the raw counts the coherence self-model is built from. Control chatter (pings, gossip) is excluded,
    /// so this reflects *load*, not liveness.
    activity: BTreeMap<Triple, u32>,
    /// This node's own relay activity (`Route` frames it originated) since the last sample — the self slot
    /// of the behavioural sample vector.
    self_activity: u32,
    /// The mutable **decoupling** shed factor `∈ [0, DECOUPLE_MAX]` (audit C6): scales this node's effective
    /// correlation down so a `Decouple` actually lowers `Φ`. `decoupled`/`escalated_coherence` dedup the
    /// homeostat notifications (which previously re-fired every diagnose).
    pub(crate) decoupling: f64,
    /// Dedup: currently in the shed (decoupled) regime — so `Decoupled` fires once on entry, not each round.
    decoupled: bool,
    /// Dedup: currently escalated on a coherence collapse — so `Escalated` fires once on entry.
    escalated_coherence: bool,
    /// Consecutive self-driven diagnoses that read over-coupled (`Verdict::Systemic`); resets to 0 on any
    /// non-over-coupled diagnosis. The `Decouple` shed only actuates once this reaches [`DECOUPLE_DWELL`] —
    /// the hysteresis that keeps the now-continuous reflex from shedding on a transient reading (#122).
    overcoupling_streak: u32,
    /// The most recent per-point relay-load sample (§6.7): the behavioural sample folded into the monitor
    /// each heartbeat, RETAINED here (the monitor consumes it, then `activity` is cleared) so a diagnosis can
    /// read the cell's current load vector for the projective load-balance prescription. All `N` points are
    /// observable from one node because its `q+1` lines cover the plane.
    pub(crate) last_sample: [f64; 7],
    /// Dedup: currently in the under-coupled (`Bind`) regime, so `Rebalance` fires once on entry (§6.7), not
    /// each round; cleared when the cell returns to the in-band collective-subject (`Hold`).
    rebalancing: bool,
    /// The §6.4 endpoint cross-attestation window: the last [`ENDPOINT_WINDOW`] rounds of per-witness
    /// liveness fresh-masks (bit `p` ⇔ that witness gossiped point `p` fresh), reconstructed each heartbeat
    /// from the corroborated `witnessed` substrate + own direct view. `attest_endpoints` reads it through
    /// [`polar::fabricators_by_persistent_freshness`] to catch a colluding vouch-fabricator keeping a dead
    /// node believed-alive — the third-order fault the plain corroboration quorum, which only *counts*
    /// vouchers, cannot see. Bounded (`≤ ENDPOINT_WINDOW` tiny arrays), so it adds no unbounded state.
    endpoint_window: VecDeque<[Option<u8>; 7]>,
    /// §6.5 partition-sensor hysteresis: consecutive diagnoses whose loss-weighted line graph is
    /// disconnected. `Verdict::Partition` is trusted only once this reaches [`PARTITION_DWELL`], so a
    /// recovery-loss transient never false-fires (resets to 0 on any connected reading).
    partition_streak: u32,
    /// The coherence `Φ` computed on the last diagnosis — exposed so the facade can spend the coarse
    /// `⌊log₉Φ⌋` reroute budget on a received cell escalation (audit R-C2) without re-diagnosing.
    pub(crate) last_phi: f64,
    /// The explicit cell members (transport coord by position) when this reflex runs a cell **embedded**
    /// in a larger plane — mirroring the facade's [`OverlayNode::cell_members`], so behavioural sampling,
    /// polar attestation, and the healing actuators (reroute/repair/quarantine) all map cell position `i`
    /// to the real member coordinate. `None` on the base cell, where position `i` is `Point::at(i)`.
    pub(crate) cell_members: Option<[Triple; 7]>,
}

impl Healer {
    /// Cell position `i` (`0..7`) → transport coordinate: the explicit member when embedded, else the base
    /// plane's `Point::at(i)`. The Healer's counterpart to [`OverlayNode::cell_coord`], so the reflex's
    /// coord lookups and actuator targets are correct for a cell seated anywhere.
    pub(crate) fn cell_coord<F: Field>(&self, i: usize) -> Triple {
        self.cell_members
            .as_ref()
            .and_then(|members| members.get(i).copied())
            .unwrap_or_else(|| Point::<F>::at(i).coords())
    }

    /// The `Φ` this reflex computed on its last diagnosis (a healthy 1.0 until the first one).
    pub(crate) fn last_phi(&self) -> f64 {
        self.last_phi
    }

    /// Create the reflex with the given self-observer (built by the facade, which knows the cell id and
    /// window). Monitor/homeostat take their base-cell defaults; all healing state starts empty.
    pub(crate) fn new(observer: SelfObserver) -> Self {
        Self {
            attested: BTreeMap::new(),
            reroute: BTreeMap::new(),
            repaired: BTreeSet::new(),
            quarantined: BTreeMap::new(),
            observer,
            monitor: BehaviorMonitor::new(7, BEHAVIOR_WINDOW),
            homeostat: Homeostat::conservative(),
            admission: AdmissionController::new(),
            last_purity: None,
            live_difficulty: None,
            admission_floor: 0,
            last_epoch: None,
            latest: None,
            window_seconds: None,
            last_stress: 0.0,
            reported_epoch: None,
            epoch_cost: None,
            activity: BTreeMap::new(),
            self_activity: 0,
            decoupling: 0.0,
            decoupled: false,
            escalated_coherence: false,
            overcoupling_streak: 0,
            last_sample: [0.0; 7],
            rebalancing: false,
            endpoint_window: VecDeque::new(),
            partition_streak: 0,
            last_phi: 1.0,
            cell_members: None,
        }
    }

    /// Count a data-relay (`Route`) frame from `from` toward its behavioural activity — the load signal
    /// folded into the coherence self-model on the next heartbeat sample. Control chatter is excluded.
    pub(crate) fn record_relay(&mut self, from: Triple) {
        let a = self.activity.entry(from).or_insert(0);
        *a = a.saturating_add(1);
    }

    /// Count a relay this node *originated* toward its own activity (the self slot of the sample vector).
    pub(crate) fn record_origination(&mut self) {
        self.self_activity = self.self_activity.saturating_add(1);
    }

    /// The transport coordinate to actually send to when addressing `to`: the self-healing co-linear
    /// survivor if `to` is being rerouted around (spec §L4), else `to` itself.
    pub(crate) fn reroute_target(&self, to: Triple) -> Triple {
        self.reroute.get(&to).copied().unwrap_or(to)
    }

    /// A recovered node (churn rejoin, spec §3.3) no longer needs rerouting or repair — clear both.
    pub(crate) fn clear_healing(&mut self, coord: Triple) {
        self.reroute.remove(&coord);
        self.repaired.remove(&coord);
    }

    /// Whether `from`'s frames must be dropped this instant because it is locally quarantined (spec §6.2,
    /// §6.4) — true only within the bounded [`QUARANTINE_TTL`] window; once that elapses the member is
    /// re-admitted here (removed) for re-evaluation, so a transient fault is not a permanent exile (C5).
    pub(crate) fn is_quarantined(&mut self, from: Triple, now: Instant) -> bool {
        if let Some(&since) = self.quarantined.get(&from) {
            if now.since(since) <= QUARANTINE_TTL {
                return true;
            }
            self.quarantined.remove(&from); // window elapsed — re-admit; re-diagnosis re-quarantines if bad
        }
        false
    }

    /// The current self-healing reroute table (down node → co-linear survivor), for observation.
    pub(crate) fn reroutes(&self) -> impl Iterator<Item = (Triple, Triple)> + '_ {
        self.reroute.iter().map(|(&k, &v)| (k, v))
    }

    /// Fold witness `from`'s polar cross-attestation into the `attested` store (spec §6.4): its 3 reported
    /// channel rates (for the pairs it mediates, `polar::polar_class`) and when they arrived. A
    /// short/malformed body is dropped whole, not partially applied (matching the canonical-decode-failure
    /// convention elsewhere, spec §7.5). Freshness is enforced at *read* time by
    /// [`attested_pairwise_rates`](Healer::attested_pairwise_rates), not here.
    pub(crate) fn apply_diag_attest(&mut self, now: Instant, from: Triple, body: &[u8]) {
        let mut rates = [0.0f64; 3];
        for (i, slot) in rates.iter_mut().enumerate() {
            let Some(bytes) = body
                .get(i * 8..i * 8 + 8)
                .and_then(|b| <[u8; 8]>::try_from(b).ok())
            else {
                return; // short/malformed body — drop, do not partially apply
            };
            *slot = f64::from_le_bytes(bytes);
        }
        self.attested.insert(from, (rates, now));
    }

    /// Fold this window's per-node relay activity into the behavioural coherence [`monitor`](Self::monitor),
    /// then reset the accumulators. Base Fano cell only (`self_index` is `Some`), where the 7-point index
    /// geometry applies; the sample's `i`-th slot is point `i`'s relay activity (this node's own for its
    /// index, else the peer's).
    pub(crate) fn sample_behavior<F: Field>(&mut self, self_index: Option<usize>) {
        let Some(self_index) = self_index else {
            return;
        };
        let mut sample = [0.0f64; 7];
        for (i, slot) in sample.iter_mut().enumerate() {
            *slot = if i == self_index {
                f64::from(self.self_activity)
            } else {
                let coord = self.cell_coord::<F>(i);
                f64::from(self.activity.get(&coord).copied().unwrap_or(0))
            };
        }
        self.monitor.record(&sample);
        // Retain this window's load vector for the §6.7 projective load-balance prescription — the monitor
        // consumes `sample` into its coherence window, but the diagnosis needs the raw per-point loads, and
        // `activity` is about to be cleared.
        self.last_sample = sample;
        self.activity.clear();
        self.self_activity = 0;
    }

    /// This node's **effective** equicorrelated correlation: the `healthy` baseline scaled down by the
    /// current `decoupling` shed factor (audit C6). Everything that computes `Φ`/`P` from a scalar
    /// correlation reads this, so a `Decouple` genuinely lowers the cell's integration.
    pub(crate) fn effective_correlation(&self, healthy: f64) -> f64 {
        healthy * (1.0 - self.decoupling)
    }

    /// Assemble the live `7×7` polar cross-attestation matrix (spec §6.4) for `diagnose`'s structural
    /// check: for each polar point `k`, the 3 rates in its class default to this node's own honest reading
    /// of `degraded` (`polar::mediator_attestation` — always internally consistent, for ANY liveness
    /// pattern), then are overridden by `k`'s own freshly-gossiped `DiagAttest`, if any (fresh within
    /// `timeout`) — the mediator is the authoritative witness of the channels it mediates. An honest
    /// override reproduces the same self-consistent triple; an equivocating one's disagrees internally by
    /// construction — and `polar::violated_classes` then localizes exactly that mediator, since each class
    /// here is filled atomically from ONE source (fallback or attestation), never a mix.
    pub(crate) fn attested_pairwise_rates<F: Field>(
        &self,
        now: Instant,
        degraded: u8,
        timeout: Duration,
    ) -> [[f64; 7]; 7] {
        let mut matrix = [[0.0f64; 7]; 7];
        for k in 0..7usize {
            let coord = self.cell_coord::<F>(k);
            let triple = match self.attested.get(&coord) {
                Some((rates, seen)) if now.since(*seen) <= timeout => *rates,
                _ => polar::mediator_attestation(k, degraded),
            };
            for ((a, b), rate) in polar::polar_class(k).into_iter().zip(triple) {
                // `a`, `b` are Fano point indices (< 7) by construction of `polar_class`; `.get_mut`
                // avoids raw bracket indexing rather than asserting that invariant with an allow.
                if let Some(cell) = matrix.get_mut(a).and_then(|row| row.get_mut(b)) {
                    *cell = rate;
                }
                if let Some(cell) = matrix.get_mut(b).and_then(|row| row.get_mut(a)) {
                    *cell = rate;
                }
            }
        }
        matrix
    }

    /// Fold this window's cell health into a `CoherenceFrame`, record it in local history, and return the
    /// effect that publishes its wire bytes. The exact 3-bit syndrome comes from `degraded`; the coherence
    /// scalars from the equicorrelated liveness model at the *effective* (post-shed) correlation
    /// (docs/design-telemetry.md §2). `epoch` is the cell's AGREED epoch, so cross-node roll-up buckets
    /// consistently (audit A3).
    pub(crate) fn emit_observation(
        &mut self,
        now: Instant,
        epoch: Epoch,
        alive_count: usize,
        degraded: u8,
        healthy_correlation: f64,
    ) -> Effect {
        let correlation = self.effective_correlation(healthy_correlation);
        let frame = self.observer.observe_liveness(
            now.as_nanos(),
            epoch.get(),
            alive_count,
            correlation,
            degraded,
            polar_gap_from_liveness(degraded), // spectral gap Δ (T-226(v)) from this window's health topology
            -1,                                // cascade forecast: none from liveness alone
        );
        Effect::Notify(Notification::Observed(frame.encode().to_vec()))
    }

    /// Publish this node's admission price here, at the operator's `floor`.
    ///
    /// Called once, when a proof-of-work gate is installed. Without it the controller runs on nothing and the
    /// price never moves — which is the correct behaviour for a node that charges no entry fee.
    pub(crate) fn set_admission(&mut self, floor: u32, live: LiveDifficulty) {
        self.admission_floor = floor;
        self.live_difficulty = Some(live);
    }

    /// Measure what an epoch advance costs this cell, and keep it.
    ///
    /// The one input to the epoch-cadence bound (`regeneration::min_epoch_period`) that cannot be read from a
    /// single window: `τ` comes from the line rates and `r_stab` from the purity, but `e₀` — the headroom an
    /// advance consumes — only exists as a *difference across the boundary*. So it is taken there: the
    /// stability radius entering an epoch, minus the radius on the first window of the next one.
    ///
    /// A negative difference is recorded as zero, not as a negative cost: a cell that came out of a reshuffle
    /// healthier than it went in was recovering from something else, and crediting the advance for it would let
    /// the floor drift below what the cell can actually sustain.
    fn measure_epoch_cost(&mut self, now: Instant, epoch: Epoch, purity: f64, n: usize, gap: f64) {
        let radius = stability::stability_radius(purity, n);
        self.latest = Some((radius, gap));
        // The observation cadence, measured rather than assumed: it is what converts a relaxation time in
        // master-equation steps into one in seconds.
        if let Some((_, then)) = self.last_purity {
            let elapsed = now.as_nanos().saturating_sub(then);
            if elapsed > 0 {
                #[allow(clippy::cast_precision_loss)] // a window is milliseconds; f64 holds it exactly
                let seconds = elapsed as f64 / 1e9;
                self.window_seconds = Some(seconds);
            }
        }
        match self.last_epoch {
            Some((seen, before)) if seen != epoch.get() => {
                self.epoch_cost = Some((before - radius).max(0.0));
                self.last_epoch = Some((epoch.get(), radius));
            }
            None => self.last_epoch = Some((epoch.get(), radius)),
            // Same epoch: keep the radius we entered it with, not this window's — the cost is measured against
            // the state the advance acted on.
            Some(_) => {}
        }
    }

    /// The shortest epoch period this cell can sustain, **in seconds**, from its own measurements.
    ///
    /// `None` until an advance has been observed *and* the observation cadence has been measured. Two of the
    /// three inputs to the bound come free from any window; the third — what an advance costs — is a difference
    /// across the epoch boundary, and a floor computed with a guessed one would read as derived and be
    /// invented.
    ///
    /// The conversion is not incidental. `Δ` counts corroborated-alive points per Fano line, so it carries no
    /// unit and `τ = 1/Δ` is a relaxation time in *observation windows*; seconds appear only by multiplying
    /// through by the measured window. A healthy cell has `Δ = 2`, and reporting its `τ = 0.5` as a wall-clock
    /// figure would have called half a step half a second.
    /// Force the measured stress — tests only.
    #[cfg(test)]
    pub(crate) fn set_stress_for_test(&mut self, stress: f64) {
        self.last_stress = stress;
    }

    /// What this node is carrying, per role, in `Role::ALL` order.
    ///
    /// Two roles have a real sensor and three do not, and the difference is kept visible rather than smoothed
    /// over. **Relay** is the count of relays this node carried since the last behavioural sample — a rate, and
    /// exactly the quantity the role exists to perform. **Storage** is the number of keys this node holds
    /// shards for. The rest report `1` where the role is offered, which is what the whole vector used to be:
    /// a measure of supply standing in for demand.
    ///
    /// Mixing a measured count with an offered one in a single vector is safe because the controller steps each
    /// role toward *its own* setpoint independently — no cross-role comparison is made — but it would be unsafe
    /// to present them as the same kind of number, which is why this says which is which.
    fn load_report(&self, held_shards: usize) -> [u16; 5] {
        let relays = u16::try_from(self.self_activity).unwrap_or(u16::MAX);
        let stored = u16::try_from(held_shards).unwrap_or(u16::MAX);
        // Role::ALL order: relay, storage, service, exit, rendezvous.
        [relays, stored, 0, 0, 0]
    }

    /// The stress this cell last measured, for a law that must decide outside the observation loop.
    pub(crate) fn stress(&self) -> f64 {
        self.last_stress
    }

    /// Take the epoch floor **if an advance has just been measured**, clearing the flag.
    ///
    /// Reported per advance rather than per window: the figure only changes when an advance is measured, and a
    /// value repeated every window would be noise an operator learns to ignore.
    fn take_epoch_floor(&mut self, epoch: Epoch) -> Option<f64> {
        if self.reported_epoch == Some(epoch.get()) || self.epoch_cost.is_none() {
            return None;
        }
        let floor = self.epoch_floor_seconds()?;
        self.reported_epoch = Some(epoch.get());
        Some(floor)
    }

    pub(crate) fn epoch_floor_seconds(&self) -> Option<f64> {
        let cost = self.epoch_cost?;
        let (radius, gap) = self.latest?;
        let window = self.window_seconds?;
        let tau_windows = if gap > 0.0 { 1.0 / gap } else { f64::INFINITY };
        Some(regeneration::min_epoch_period(tau_windows, cost, radius) * window)
    }

    /// What this node is carrying, as an effect — emitted every observation, coherence or not.
    pub(crate) fn load_effect(&self, held_shards: usize) -> Effect {
        Effect::Notify(Notification::LoadReport { per_role: self.load_report(held_shards) })
    }

    /// Run the per-observation control laws that need the cell's **coherence matrix**.
    ///
    /// Separate from the load report, which does not: a node knows how many keys it holds and how many relays
    /// it carried whether or not `Γ_net` has enough samples to exist yet. Folding the two together made the
    /// role controller's only real input wait on a quantity it never needed — caught by a test that asked a
    /// fresh node what it was carrying and got nothing.
    ///
    /// Grouped because they share one shape — each reads the cell's own state this window and either acts on it
    /// or tells someone who can. Kept out of `diagnose`, which is the *diagnosis*: sensing a fault and healing
    /// it is a different job from governing a price, a cadence, or a role.
    fn control_laws(
        &mut self,
        now: Instant,
        epoch: Epoch,
        purity: f64,
        n: usize,
        degraded: u8,
    ) -> Vec<Effect> {
        let gap = polar_gap_from_liveness(degraded);
        self.price_admission(now, purity, n, gap);
        self.measure_epoch_cost(now, epoch, purity, n, gap);
        let mut out = Vec::new();
        if let Some(seconds) = self.take_epoch_floor(epoch) {
            // A finite floor becomes milliseconds; an infinite one is the absent value, because "no
            // sustainable cadence" is not a very large period.
            #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
            let millis = seconds.is_finite().then(|| (seconds * 1000.0).max(0.0) as u64);
            out.push(Effect::Notify(Notification::EpochFloor { millis }));
        }
        out
    }

    /// Move this node's admission price to what its own measured stress justifies.
    ///
    /// The **actuator** of DDoS homeostasis. T-104 says a cell survives sustained noise iff `‖h‖ < κ·r_stab`,
    /// and every other response — the homeostat's band control, the healing plan's reroute and repair — acts on
    /// `κ` and on internal structure. This is the only one that acts on `‖h‖`, by making entry cost more.
    ///
    /// Everything it needs is already sensed or known: the purity and `N` from the measured `Γ_net`, the
    /// regeneration rate from the homeostat's own gain, and the baseline dissipation from this window's
    /// liveness topology. The one thing it must remember is the previous purity, because the disturbance is
    /// inferred from the *rate*, not the level.
    ///
    /// A node with no proof-of-work admission has no price to move, so this is inert there rather than
    /// pretending — and the controller can only ever raise the operator's floor, never open a door the
    /// operator closed.
    fn price_admission(&mut self, now: Instant, purity: f64, n: usize, lambda: f64) {
        let Some(live) = self.live_difficulty.clone() else { return };
        let nanos = now.as_nanos();
        let Some((previous, then)) = self.last_purity.replace((purity, nanos)) else {
            return; // the first window has no rate; a controller cannot act on one sample
        };
        let elapsed = nanos.saturating_sub(then);
        if elapsed == 0 {
            return;
        }
        #[allow(clippy::cast_precision_loss)] // a window is milliseconds; f64 holds it exactly
        let seconds = elapsed as f64 / 1e9;
        let kappa = self.homeostat.gain();
        let rate = (purity - previous) / seconds;
        let disturbance =
            inferred_disturbance(purity, rate, lambda, kappa, stability::p_opt(n), n);
        let stress = stability::stress(stability::stability_radius(purity, n), kappa, disturbance);
        self.last_stress = stress;
        // The window is the retention unit: the excursion decays as `(1 − κ·Δt)` over it, and releasing the
        // price faster than the cell recovers is precisely what makes the controller oscillate.
        let retention = 1.0 - (kappa * seconds).clamp(0.0, 1.0);
        live.set(self.admission.observe(self.admission_floor, stress, retention));
    }

    /// Diagnose the sensed cell snapshot (`self_index, degraded, alive_count`, produced by the facade's
    /// liveness sensing) and actuate any healing — the DIAKRISIS reflex proper. Feeds the *measured*
    /// behavioural `Γ_net` (the #74 unification) plus the live polar cross-attestation into `diagnose`,
    /// runs the verdict→plan→actuate path (over-coupling gated by the [`DECOUPLE_DWELL`] hysteresis, #122),
    /// then the homeostat's re-integration/escalation bands, and finally the mandatory self-observation.
    #[allow(clippy::too_many_arguments)] // the sensed cell snapshot: index, degraded, alive, lines, config, epoch
    pub(crate) fn diagnose<F: Field>(
        &mut self,
        now: Instant,
        self_index: usize,
        degraded: u8,
        alive_count: usize,
        healthy_lines: Option<u8>,
        config: &Config,
        epoch: Epoch,
    ) -> Vec<Effect> {
        // The base node senses liveness, and — the #74 unification — the *measured* behavioural coherence
        // `Γ_net` (the relay-activity self-model). Feeding `Γ_net` into `diagnose` makes its Systemic
        // (over-coupling) verdict fire on the same signal the homeostat acts on, so there is one
        // over-coupling authority, not a dormant liveness-only arm beside a separate behavioural check.
        // (Partition/cascade still need the global cross-attestation view, not this local sense alone.)
        let measured = self.monitor.coherence();
        // The structural (Byzantine) check (spec §6.4 + §6.2): the live polar cross-attestation matrix,
        // assembled from gossiped `DiagAttest` reports (§98). `diagnose` runs the 14 free polar sum-rules
        // against it FIRST, ahead of the syndrome localizer — an equivocating mediator's own report is
        // internally inconsistent and is caught and localized here; an honest cell's is always consistent,
        // so this never pre-empts the ordinary crash/churn path below, however many members are down.
        let pairwise_rates =
            self.attested_pairwise_rates::<F>(now, degraded, config.liveness_timeout);
        // §6.5 partition sensor (V14): `healthy_lines` names which cell lines carry live inter-node
        // connectivity, derived from the *measured* per-channel loss (the #106 grey substrate) — an
        // INDEPENDENT signal, not the node-liveness `degraded` mask (that would be redundant with the crash
        // path). Persistence guard: a disconnected loss-weighted graph is only trusted after
        // [`PARTITION_DWELL`] consecutive readings, so a recovery-loss transient (a just-healed node whose
        // lines still read cut for a round) never false-fires; below the dwell we present the cell as fully
        // connected so no premature `Verdict::Partition` escapes. Partition-resistance (one lossy line still
        // reads λ₂=4) means only a sustained lossy line-COVER — a real incipient split, nodes still alive —
        // ever reaches the verdict.
        // A partition candidate is only meaningful when the cell is ALL-ALIVE: if any node is down
        // (`degraded != 0`) the disconnection is explained by the crash and handled by the node-fault path, so
        // it must NOT build the partition streak (else a crash+recovery churn would accumulate the streak and
        // false-fire on the recovery transient). Only a sustained *all-alive* disconnection — a real incipient
        // split, nodes still up — accumulates.
        let disconnected =
            degraded == 0 && healthy_lines.is_some_and(|h| !partition::is_connected(h));
        self.partition_streak = if disconnected {
            self.partition_streak.saturating_add(1)
        } else {
            0
        };
        let trusted_lines = match healthy_lines {
            Some(_) if disconnected && self.partition_streak < PARTITION_DWELL => Some(0x7F),
            other => other,
        };
        let verdict = diagnose(&Observation {
            degraded,
            pairwise_rates: Some(pairwise_rates),
            coherence: measured.clone(),
            healthy_lines: trusted_lines,
        });

        // Hysteresis for the over-coupling shed (audit #122): count consecutive over-coupled diagnoses,
        // resetting on any non-over-coupled one. `Decouple` actuates only once this reaches DECOUPLE_DWELL,
        // so the now-continuous reflex sheds on *sustained* over-coupling, not a single transient reading.
        self.overcoupling_streak = if matches!(verdict, fanos_diakrisis::Verdict::Systemic) {
            self.overcoupling_streak.saturating_add(1)
        } else {
            0
        };

        let mut effects = alloc::vec![Effect::Notify(Notification::Verdict(verdict.clone()))];
        if config.self_healing {
            // Φ from the cell's live membership on the equicorrelated stratum, at the *effective*
            // (post-shed) correlation — so a prior `Decouple` has genuinely lowered it (audit C6). Gates
            // the reroute-depth budget.
            let phi = phi_equicorrelated(
                alive_count,
                self.effective_correlation(config.healthy_correlation),
            );
            self.last_phi = phi; // exposed to the facade's parent-stratum reflex (R-C2)
            let plan = plan_healing(&verdict, self_index, degraded, phi);
            if !plan.is_empty() {
                self.observer.note_healing();
            }
            // Over-coupling actuation (`Decouple`) flows through this verdict→plan path, gated by the dwell
            // hysteresis above; `apply_healing_plan` raises the mutable decoupling state and dedups the
            // notification (audit C6/#122). Crash/Byzantine actions in the plan are never gated.
            let decouple_ready = self.overcoupling_streak >= DECOUPLE_DWELL;
            effects.extend(self.apply_healing_plan::<F>(now, &plan, decouple_ready));

            // The homeostat covers the bands the Systemic verdict does not: **re-integration** once the
            // measured `Γ_net` is back in (or below) the band (Bind/Hold — decay the shed), and
            // **escalation** on a coherence *collapse* (`P ≤ 2/N`). Over-coupling is the verdict path's.
            if let Some(coherence) = measured {
                let m = coherence.measures();
                effects.extend(self.control_laws(now, epoch, m.purity, coherence.n(), degraded));
                match self
                    .homeostat
                    .control(m.purity, coherence.mean_correlation(), coherence.n())
                {
                    BandControl::Escalate => {
                        if !self.escalated_coherence {
                            self.escalated_coherence = true;
                            self.observer.note_healing();
                            effects.push(Effect::Notify(Notification::Escalated(0)));
                        }
                    }
                    BandControl::Decouple { .. } => {
                        // Actuated via the verdict→plan path above; only clear the escalation latch.
                        self.escalated_coherence = false;
                    }
                    band @ (BandControl::Bind { .. } | BandControl::Hold) => {
                        // In or below the band: let any prior shedding decay back toward the baseline
                        // coupling, and notify `Bound` once when fully re-integrated.
                        self.decoupling *= DECOUPLE_DECAY;
                        if self.decoupling < 1e-9 {
                            self.decoupling = 0.0;
                        }
                        self.escalated_coherence = false;
                        if self.decoupled && self.decoupling == 0.0 {
                            self.decoupled = false;
                            effects.push(Effect::Notify(Notification::Bound));
                        }
                        // §6.7 differential-DDoS response: the under-coupled `Bind` (`Aggregate`) band is the
                        // regime a load hotspot induces by decorrelating the cell. Publish the projective load
                        // state the node sensed — its per-point relay load over the whole cell (observable
                        // because its q+1 lines cover the plane) — once on ENTERING the band (deduped). The
                        // derived response is `loadbalance::balance_exact(loads)` = the uniform mean, driving
                        // the hotspot into the whole cell at the projective contraction `λ₂ = 2/9`. `Hold` is
                        // the healthy in-band collective subject: clear the latch so a later Bind re-publishes.
                        if matches!(band, BandControl::Bind { .. }) {
                            if !self.rebalancing {
                                self.rebalancing = true;
                                let loads = self.last_sample.map(|x| x.round() as u32);
                                effects.push(Effect::Notify(Notification::Rebalance { loads }));
                            }
                        } else {
                            self.rebalancing = false;
                        }
                    }
                }
            }
        }
        // Mandatory self-observation: diagnosis cannot happen without observing.
        effects.push(self.emit_observation(
            now,
            epoch,
            alive_count,
            degraded,
            config.healthy_correlation,
        ));
        effects
    }

    /// Apply a [`HealingPlan`], mutating the reroute / repaired / quarantine state and emitting a
    /// notification for each *new* corrective action (idempotent across repeated rounds).
    pub(crate) fn apply_healing_plan<F: Field>(
        &mut self,
        now: Instant,
        plan: &fanos_diakrisis::HealingPlan,
        decouple_ready: bool,
    ) -> Vec<Effect> {
        let mut effects = Vec::new();
        for action in &plan.actions {
            match *action {
                HealingAction::Reroute { around, via } => {
                    let around_c = self.cell_coord::<F>(around);
                    let via_c = self.cell_coord::<F>(via);
                    if self.reroute.insert(around_c, via_c) != Some(via_c) {
                        effects.push(Effect::Notify(Notification::Rerouted {
                            around: around_c,
                            via: via_c,
                        }));
                    }
                }
                HealingAction::Repair { node, .. } => {
                    let node_c = self.cell_coord::<F>(node);
                    if self.repaired.insert(node_c) {
                        effects.push(Effect::Notify(Notification::Repaired(node_c)));
                    }
                }
                HealingAction::Quarantine { node } => {
                    let node_c = self.cell_coord::<F>(node);
                    effects.extend(self.quarantine(node_c, now));
                }
                HealingAction::Decouple => {
                    // Real correlation-shedding (audit C6), gated by the dwell hysteresis (#122): only once
                    // over-coupling has held for DECOUPLE_DWELL consecutive diagnoses do we raise the
                    // mutable decoupling factor (capped), lowering the effective correlation feeding `Φ`
                    // next round. Notify once on *entering* the shed regime (dedup), not each round.
                    if decouple_ready {
                        self.decoupling = (self.decoupling + DECOUPLE_STEP).min(DECOUPLE_MAX);
                        if !self.decoupled {
                            self.decoupled = true;
                            effects.push(Effect::Notify(Notification::Decoupled));
                        }
                    }
                }
                HealingAction::Escalate { unrecoverable } => {
                    effects.push(Effect::Notify(Notification::Escalated(unrecoverable)));
                }
            }
        }
        effects
    }

    /// Locally quarantine `node_c` (spec §6.2/§6.4): drop its frames for the bounded re-admission window,
    /// emitting a `Quarantined` notification only on a *new* distrust (idempotent across rounds). The single
    /// quarantine actuator shared by the mediator model (`violated_classes`, via the healing plan) and the
    /// endpoint fabrication detector ([`attest_endpoints`]) — one reason for a member's frames to be dropped.
    /// Clear any quarantine tag on `node_c`, re-admitting it immediately rather than at TTL expiry.
    ///
    /// Used when a coordinate's **occupant changes** (audit R-M1): a tag belongs to an identity, and the arriving
    /// identity has not earned its predecessor's distrust. Silent — re-admission is the absence of a verdict, not a
    /// verdict, so it emits no notification.
    pub(crate) fn readmit(&mut self, node_c: Triple) {
        self.quarantined.remove(&node_c);
    }

    pub(crate) fn quarantine(&mut self, node_c: Triple, now: Instant) -> Option<Effect> {
        self.quarantined
            .insert(node_c, now)
            .is_none()
            .then_some(Effect::Notify(Notification::Quarantined(node_c)))
    }

    /// The **§6.4 endpoint cross-attestation, live** (#106). Fold this heartbeat's per-witness liveness
    /// fresh-masks (built by the facade from the corroborated `witnessed` substrate) into the bounded window
    /// and, once it is full, run the directional fabrication detector: quarantine any witness that
    /// *persistently* vouches a node fresh while a firm consensus reports it stale — a colluding
    /// vouch-fabricator keeping a dead node believed-alive, the fault the plain corroboration quorum (which
    /// only counts vouchers) is defeated by. `subjects` are the points the judge cannot itself directly
    /// confirm alive (`!own_fresh_mask`), so a node it can see is never adjudicated — the honest-node
    /// safeguard. Dual to the quorum; complements the mediator model's equivocation catch. Below a full
    /// window there is not enough history to judge persistence, so nothing fires (churn-safe cold start).
    pub(crate) fn attest_endpoints<F: Field>(
        &mut self,
        now: Instant,
        round: [Option<u8>; 7],
        subjects: u8,
    ) -> Vec<Effect> {
        self.endpoint_window.push_back(round);
        while self.endpoint_window.len() > ENDPOINT_WINDOW {
            self.endpoint_window.pop_front();
        }
        if self.endpoint_window.len() < ENDPOINT_WINDOW {
            return Vec::new();
        }
        let window: Vec<[Option<u8>; 7]> = self.endpoint_window.iter().copied().collect();
        let mut effects = Vec::new();
        for idx in polar::fabricators_by_persistent_freshness(&window, ENDPOINT_MIN_STALE, subjects)
        {
            let node_c = self.cell_coord::<F>(idx);
            effects.extend(self.quarantine(node_c, now));
        }
        effects
    }
}

