//! The **DIAKRISIS self-healing reflex** — the node's verified reflex layer, factored out of `OverlayNode`.
//!
//! Split from `overlay.rs` (audit #125 decompose, task 7a): the behavioural coherence self-model, the over-coupling
//! homeostat, and the crash/Byzantine healing state (reroute / repair / quarantine) with the live polar
//! cross-attestation it diagnoses from. `OverlayNode` keeps the *liveness sensing* — the peer substrate,
//! `coord_alive`/`cell_liveness`/`health_view`, the corroboration cache — and hands this module a **sensed** cell
//! snapshot; everything the reflex then does with that snapshot lives here.
//!
//! Deliberately not generic over `F`: the state is all concrete, and the few methods needing the cell's
//! index-addressed geometry take `<F>` per call.

use crate::overlay::{
    Config, DECOUPLE_DECAY, BAND_DWELL, ENDPOINT_MIN_STALE, decouple_ceiling,
    ENDPOINT_WINDOW, PARTITION_DWELL, QUARANTINE_TTL, polar_gap_from_liveness,
};
use crate::ports::{Duration, Effect, Escalation, Instant, Notification};

use alloc::collections::{BTreeMap, BTreeSet, VecDeque};
use alloc::vec::Vec;

use fanos_diakrisis::coherence::phi_at;
use fanos_diakrisis::monitor::BehaviorMonitor;
use fanos_diakrisis::partition;
use fanos_diakrisis::polar;
use fanos_core::LiveDifficulty;
use fanos_core::roles::{Role, RoleReading};
use fanos_diakrisis::regeneration;
use fanos_diakrisis::stability::{self, AdmissionController, inferred_disturbance};
use fanos_diakrisis::{BandControl, HealingAction, Homeostat, Observation, diagnose, plan_healing};
use fanos_field::Field;
use fanos_geometry::{Point, Triple};
use fanos_primitives::Epoch;
use fanos_telemetry::SelfObserver;

/// The DIAKRISIS self-healing reflex factored out of [`OverlayNode`] (audit #125 decompose): the node's
/// **verified reflex layer** (see [[synarc-node-architecture]]) — behavioural coherence self-model, the
/// over-coupling homeostat, and the crash/Byzantine healing state (reroute / repair / quarantine) with the
/// live polar cross-attestation it diagnoses from. The facade owns the *liveness sensing* (the `peers`
/// substrate + `coord_alive`/`cell_liveness`/`health_view` + the `witnessed` corroboration cache) and
/// hands this a **sensed** cell snapshot (`self_index, degraded, alive_count`); this owns everything the
/// reflex then does with it. Not generic over `F`: its state is all concrete, and the few methods that
/// need the cell's index-addressed geometry take `<F>` per call.
pub(crate) struct Healer {
    /// Live polar cross-attestation (spec §6.4, §6.2): the freshest `DiagAttest` report gossiped by each
    /// OTHER cell member — its own honest reading of the 3 channel rates it mediates (`polar::polar_class`),
    /// and when it arrived. [`attested_pairwise_rates`](Healer::attested_pairwise_rates) assembles these
    /// (falling back to this node's own reading for any member it hasn't freshly heard from) into the
    /// `Observation.pairwise_rates` matrix `diagnose` feeds the 14 free polar sum-rule alarms. An honest
    /// report's 3 values always agree (`polar::mediator_attestation`); an equivocating member's disagree
    /// internally, and `polar::violated_classes` then localizes exactly it.
    attested: BTreeMap<Triple, ([f64; 3], Instant)>,
    /// Self-healing routing state: to reach the (down) key coordinate, contact the value coordinate — the
    /// co-linear survivor from the projective LRC reroute (spec §L4).
    reroute: BTreeMap<Triple, Triple>,
    /// Nodes whose shard this cell has regenerated by peeling (spec §6.3), for observability.
    repaired: BTreeSet<Triple>,
    /// Members locally distrusted after a polar-rule violation (spec §6.2); their frames are dropped
    /// pending parental re-provisioning.
    pub(crate) quarantined: BTreeMap<Triple, Instant>,
    /// Mandatory per-node self-observation (`fanos_telemetry`): every diagnosis folds the cell's health
    /// into a `CoherenceFrame` and records it into bounded local history. Not optional — the reflexive loop
    /// cannot diagnose without observing (docs/design-telemetry.md).
    observer: SelfObserver,
    /// The behavioural coherence monitor: a bounded window of per-node relay activity, read as the cell's
    /// real `Γ_net` so the [`Homeostat`] runs on *measured* correlation, not the liveness proxy (base cell).
    monitor: BehaviorMonitor,
    /// The coherence homeostat this node runs on its behavioural self-model — the sense→act seam, with the
    /// monitor sensing and `diagnose` actuating its band-keeping decision.
    homeostat: Homeostat,
    /// The DDoS admission-price controller (T-104): raises the cost of joining this node as its own measured
    /// stress rises, and releases it at the cell's recovery constant. See `fanos_diakrisis::stability`.
    admission: AdmissionController,
    /// The previous window's `(purity, timestamp)`, so the disturbance can be inferred from the *rate* the
    /// purity is moving rather than from its level. The level only moves after damage; the rate carries an
    /// attack on the first window, which is the difference between a controller that saves a cell and one that
    /// watches it die (measured — `stability::the_admission_law_saves_a_cell_that_would_otherwise_die`).
    last_purity: Option<(f64, u64)>,
    /// Where the controller's decision is published for the admission gate to read. `None` when this node runs
    /// no proof-of-work admission, in which case there is no price to move.
    live_difficulty: Option<LiveDifficulty>,
    /// The operator's configured floor, which the controller may raise above but never go under.
    admission_floor: u32,
    /// The epoch this cell was last observed in, and the stability radius it held entering it — the two
    /// readings the cost of an epoch advance is measured from. See [`epoch_floor`](Self::epoch_floor).
    last_epoch: Option<(u64, f64)>,
    /// The most recent `(stability radius, spectral gap)` — the two per-window inputs to the epoch floor.
    latest: Option<(f64, f64)>,
    /// The stress this cell last measured — the input every control law here shares.
    ///
    /// Kept because two laws now read it at different moments: the admission price is set inside the
    /// observation that computes it, while a read's fan-out is decided whenever a `Get` arrives, which is not
    /// synchronised to anything.
    last_stress: f64,
    /// The epoch whose floor has already been reported, so each advance is reported exactly once.
    ///
    /// An epoch rather than a flag: the question is "have I told anyone about *this* advance", and the epoch
    /// answers it directly while a boolean only records that something happened.
    reported_epoch: Option<u64>,
    /// How long one observation window lasts, in seconds, measured from consecutive observations.
    ///
    /// The **unit bridge**, and it is load-bearing. The polar gap `Δ` is a count of corroborated-alive points
    /// per Fano line (a healthy cell gives `Δ = 2`), so it is *dimensionless* and `τ = 1/Δ` is a relaxation
    /// time in master-equation steps, not in seconds. One step is one observation window, so seconds only
    /// appear by multiplying through by this. Reporting `1/Δ` as a wall-clock time would have called half a
    /// step half a second.
    window_seconds: Option<f64>,
    /// The headroom the most recent epoch advance was measured to consume, and the shortest period that cost
    /// makes sustainable. `None` until a first advance has been observed — a floor derived from no measurement
    /// would be a guess wearing a derivation.
    epoch_cost: Option<f64>,
    /// Per-peer **data-relay** activity (`Route` frames) accumulated since the last behavioural sample —
    /// the raw counts the coherence self-model is built from. Control chatter (pings, gossip) is excluded,
    /// so this reflects *load*, not liveness.
    activity: BTreeMap<Triple, u32>,
    /// This node's own relay activity (`Route` frames it originated) since the last sample — the self slot
    /// of the behavioural sample vector.
    self_activity: u32,
    /// The mutable **decoupling** shed factor `∈ [0, DECOUPLE_MAX]` (audit C6): scales this node's effective
    /// correlation down so a `Decouple` actually lowers `Φ`. `decoupled`/`escalated_coherence` dedup the
    /// homeostat notifications (which previously re-fired every diagnose).
    pub(crate) decoupling: f64,
    /// Dedup: currently in the shed (decoupled) regime — so `Decoupled` fires once on entry, not each round.
    decoupled: bool,
    /// Dedup: currently escalated on a coherence collapse — so `Escalated` fires once on entry.
    escalated_coherence: bool,
    /// Consecutive self-driven diagnoses that read over-coupled (`Verdict::Systemic`); resets to 0 on any
    /// non-over-coupled diagnosis. The `Decouple` shed only actuates once this reaches [`BAND_DWELL`] —
    /// the hysteresis that keeps the now-continuous reflex from shedding on a transient reading (#122).
    /// Consecutive diagnoses of the SAME homeostat band, and which band that was — the hysteresis every
    /// band branch is gated by (#100). See `BAND_DWELL`.
    band_streak: u32,
    last_band: Option<core::mem::Discriminant<BandControl>>,
    /// The loop's derived resolution, from [`Config::control_confidence`] — kept because the shed ceiling
    /// needs it at actuation time and the config is not threaded that far down.
    control_confidence: f64,
    /// The observation window this node was configured for, from [`Config::behavior_window`].
    behavior_window: usize,
    /// The cell's own measured mean off-diagonal correlation from the last full-window diagnosis, or `None`
    /// until it has one. See [`baseline_correlation`](Healer::baseline_correlation).
    measured_correlation: Option<f64>,
    /// The most recent per-point relay-load sample (§6.7): the behavioural sample folded into the monitor
    /// each heartbeat, RETAINED here (the monitor consumes it, then `activity` is cleared) so a diagnosis can
    /// read the cell's current load vector for the projective load-balance prescription. All `N` points are
    /// observable from one node because its `q+1` lines cover the plane.
    pub(crate) last_sample: [f64; 7],
    /// Dedup: currently in the under-coupled (`Bind`) regime, so `Rebalance` fires once on entry (§6.7), not
    /// each round; cleared when the cell returns to the in-band collective-subject (`Hold`).
    rebalancing: bool,
    /// The §6.4 endpoint cross-attestation window: the last [`ENDPOINT_WINDOW`] rounds of per-witness
    /// liveness fresh-masks (bit `p` ⇔ that witness gossiped point `p` fresh), reconstructed each heartbeat
    /// from the corroborated `witnessed` substrate + own direct view. `attest_endpoints` reads it through
    /// [`polar::fabricators_by_persistent_freshness`] to catch a colluding vouch-fabricator keeping a dead
    /// node believed-alive — the third-order fault the plain corroboration quorum, which only *counts*
    /// vouchers, cannot see. Bounded (`≤ ENDPOINT_WINDOW` tiny arrays), so it adds no unbounded state.
    endpoint_window: VecDeque<[Option<u8>; 7]>,
    /// §6.5 partition-sensor hysteresis: consecutive diagnoses whose loss-weighted line graph is
    /// disconnected. `Verdict::Partition` is trusted only once this reaches [`PARTITION_DWELL`], so a
    /// recovery-loss transient never false-fires (resets to 0 on any connected reading).
    partition_streak: u32,
    /// The coherence `Φ` computed on the last diagnosis — exposed so the facade can spend the coarse
    /// `⌊log₉Φ⌋` reroute budget on a received cell escalation (audit R-C2) without re-diagnosing.
    pub(crate) last_phi: f64,
    /// The explicit cell members (transport coord by position) when this reflex runs a cell **embedded**
    /// in a larger plane — mirroring the facade's [`OverlayNode::cell_members`], so behavioural sampling,
    /// polar attestation, and the healing actuators (reroute/repair/quarantine) all map cell position `i`
    /// to the real member coordinate. `None` on the base cell, where position `i` is `Point::at(i)`.
    pub(crate) cell_members: Option<[Triple; 7]>,
}

impl Healer {
    /// Cell position `i` (`0..7`) → transport coordinate: the explicit member when embedded, else the base
    /// plane's `Point::at(i)`. The Healer's counterpart to [`OverlayNode::cell_coord`], so the reflex's
    /// coord lookups and actuator targets are correct for a cell seated anywhere.
    pub(crate) fn cell_coord<F: Field>(&self, i: usize) -> Triple {
        self.cell_members
            .as_ref()
            .and_then(|members| members.get(i).copied())
            .unwrap_or_else(|| Point::<F>::at(i).coords())
    }

    /// The `Φ` this reflex computed on its last diagnosis (a healthy 1.0 until the first one).
    pub(crate) fn last_phi(&self) -> f64 {
        self.last_phi
    }

    /// Create the reflex with the given self-observer (built by the facade, which knows the cell id and
    /// window). Monitor/homeostat take their base-cell defaults; all healing state starts empty.
    pub(crate) fn new(observer: SelfObserver, behavior_window: usize, control_confidence: f64) -> Self {
        Self {
            attested: BTreeMap::new(),
            reroute: BTreeMap::new(),
            repaired: BTreeSet::new(),
            quarantined: BTreeMap::new(),
            observer,
            monitor: BehaviorMonitor::new(7, behavior_window),
            homeostat: Homeostat::conservative(),
            admission: AdmissionController::new(),
            last_purity: None,
            live_difficulty: None,
            admission_floor: 0,
            last_epoch: None,
            latest: None,
            window_seconds: None,
            last_stress: 0.0,
            reported_epoch: None,
            epoch_cost: None,
            activity: BTreeMap::new(),
            self_activity: 0,
            decoupling: 0.0,
            decoupled: false,
            escalated_coherence: false,
            band_streak: 0,
            last_band: None,
            control_confidence,
            behavior_window,
            measured_correlation: None,
            last_sample: [0.0; 7],
            rebalancing: false,
            endpoint_window: VecDeque::new(),
            partition_streak: 0,
            last_phi: 1.0,
            cell_members: None,
        }
    }

    /// **The seating changed — drop everything addressed by it** (#153).
    ///
    /// An epoch boundary re-draws every node's VRF coordinate, so a cell position keeps its *name* and
    /// changes its *occupant* (`P(a seat keeps its node) = 1/q²+q+1`; `1/7` on the base cell). Every piece of
    /// state here that is addressed by a coordinate or a cell index therefore stops describing what its
    /// address says it describes, at one instant, for all of it at once.
    ///
    /// The sharp one is the behavioural window, and it was measured rather than argued
    /// (`scratchpad/reshuffle_phi.py`, 400 runs): `sample[i] = activity[cell_coord(i)]`, so `W = 178`
    /// samples after a turn the per-slot series is a splice of two assignments. On an *exchangeable* cell —
    /// identical mean load — a column permutation is provably harmless and the reading moves by `+0.002`,
    /// which is why no test ever saw this. On a cell with a 5× load spread the mean off-diagonal `r` falls
    /// from `+0.835` to `+0.170`, and at 20× to `+0.069`: a displacement of three to four and a half
    /// **band-widths** (the collective-subject band is `0.169` wide), downward, into `Bind`/`Rebalance`, for
    /// 173 of the 179 samples of the splice. `BAND_DWELL = 3` is 1.5 s and cannot help against 89 s.
    ///
    /// What is dropped is exactly **what a seat addresses**; what is kept is what a scalar does:
    ///
    /// * dropped — the coherence window, the endpoint fresh-mask window, the partial activity accumulator,
    ///   the retained load vector, the last measured correlation, both dwell streaks, the reroute table and
    ///   the repaired set. Every one is keyed by a coordinate or a cell index.
    /// * kept — `decoupling` and its dedup flags. A shed is a scalar actuation, not a claim about any
    ///   position, and dropping it would re-couple a cell that still needs shedding at the exact moment the
    ///   node has no reading to justify re-applying it. An actuation persists until a *new* measurement
    ///   overrides it.
    /// * kept — `last_epoch` / `epoch_cost` / `window_seconds`, which measure the boundary itself and so
    ///   must survive it. The advance's cost is now read from a full post-boundary window instead of from a
    ///   spliced one, so it stops charging the advance for the splice artefact.
    /// * kept, and this is the one to be careful about — **`quarantined`**. Audit R-M1 gave the driver
    ///   ownership of distrust: it holds the verdict by *identity* (`Distrust::by_identity`, keyed off the
    ///   authenticated coordinate proof) and re-issues [`Command::Quarantine`]/[`Command::Readmit`] as
    ///   occupants move. Clearing the tag here would silently undo that re-application and hand a Byzantine
    ///   member a clean slate every epoch.
    ///
    /// [`Command::Quarantine`]: fanos_ports::Command::Quarantine
    /// [`Command::Readmit`]: fanos_ports::Command::Readmit
    pub(crate) fn on_seating_changed(&mut self) {
        self.monitor.clear();
        self.endpoint_window.clear();
        self.activity.clear();
        self.self_activity = 0;
        self.last_sample = [0.0; 7];
        self.measured_correlation = None;
        self.band_streak = 0;
        self.last_band = None;
        self.partition_streak = 0;
        self.reroute.clear();
        self.repaired.clear();
    }

    /// Count a data-relay (`Route`) frame from `from` toward its behavioural activity — the load signal
    /// folded into the coherence self-model on the next heartbeat sample. Control chatter is excluded.
    pub(crate) fn record_relay(&mut self, from: Triple) {
        let a = self.activity.entry(from).or_insert(0);
        *a = a.saturating_add(1);
    }

    /// Count a relay this node *originated* toward its own activity (the self slot of the sample vector).
    pub(crate) fn record_origination(&mut self) {
        self.self_activity = self.self_activity.saturating_add(1);
    }

    /// The transport coordinate to actually send to when addressing `to`: the self-healing co-linear
    /// survivor if `to` is being rerouted around (spec §L4), else `to` itself.
    pub(crate) fn reroute_target(&self, to: Triple) -> Triple {
        self.reroute.get(&to).copied().unwrap_or(to)
    }

    /// A recovered node (churn rejoin, spec §3.3) no longer needs rerouting or repair — clear both.
    pub(crate) fn clear_healing(&mut self, coord: Triple) {
        self.reroute.remove(&coord);
        self.repaired.remove(&coord);
    }

    /// Whether `from`'s frames must be dropped this instant because it is locally quarantined (spec §6.2,
    /// §6.4) — true only within the bounded [`QUARANTINE_TTL`] window; once that elapses the member is
    /// re-admitted here (removed) for re-evaluation, so a transient fault is not a permanent exile (C5).
    pub(crate) fn is_quarantined(&mut self, from: Triple, now: Instant) -> bool {
        if let Some(&since) = self.quarantined.get(&from) {
            if now.since(since) <= QUARANTINE_TTL {
                return true;
            }
            self.quarantined.remove(&from); // window elapsed — re-admit; re-diagnosis re-quarantines if bad
        }
        false
    }

    /// The current self-healing reroute table (down node → co-linear survivor), for observation.
    pub(crate) fn reroutes(&self) -> impl Iterator<Item = (Triple, Triple)> + '_ {
        self.reroute.iter().map(|(&k, &v)| (k, v))
    }

    /// Fold witness `from`'s polar cross-attestation into the `attested` store (spec §6.4): its 3 reported
    /// channel rates (for the pairs it mediates, `polar::polar_class`) and when they arrived. A
    /// short/malformed body is dropped whole, not partially applied (matching the canonical-decode-failure
    /// convention elsewhere, spec §7.5). Freshness is enforced at *read* time by
    /// [`attested_pairwise_rates`](Healer::attested_pairwise_rates), not here.
    pub(crate) fn apply_diag_attest(&mut self, now: Instant, from: Triple, body: &[u8]) {
        let mut rates = [0.0f64; 3];
        for (i, slot) in rates.iter_mut().enumerate() {
            let Some(bytes) = body
                .get(i * 8..i * 8 + 8)
                .and_then(|b| <[u8; 8]>::try_from(b).ok())
            else {
                return; // short/malformed body — drop, do not partially apply
            };
            *slot = f64::from_le_bytes(bytes);
        }
        self.attested.insert(from, (rates, now));
    }

    /// Fold this window's per-node relay activity into the behavioural coherence [`monitor`](Self::monitor),
    /// then reset the accumulators. Base Fano cell only (`self_index` is `Some`), where the 7-point index
    /// geometry applies; the sample's `i`-th slot is point `i`'s relay activity (this node's own for its
    /// index, else the peer's).
    pub(crate) fn sample_behavior<F: Field>(&mut self, self_index: Option<usize>) {
        let Some(self_index) = self_index else {
            return;
        };
        let mut sample = [0.0f64; 7];
        for (i, slot) in sample.iter_mut().enumerate() {
            *slot = if i == self_index {
                f64::from(self.self_activity)
            } else {
                let coord = self.cell_coord::<F>(i);
                f64::from(self.activity.get(&coord).copied().unwrap_or(0))
            };
        }
        self.monitor.record(&sample);
        // Retain this window's load vector for the §6.7 projective load-balance prescription — the monitor
        // consumes `sample` into its coherence window, but the diagnosis needs the raw per-point loads, and
        // `activity` is about to be cleared.
        self.last_sample = sample;
        self.activity.clear();
        self.self_activity = 0;
    }

    /// **Hysteresis for every band branch, not only the over-coupled one** (#100): advance the streak of
    /// consecutive diagnoses of the *same* band and report whether it has reached [`BAND_DWELL`].
    ///
    /// Any change of band restarts the count, and no band at all (a window not yet full) clears it. The
    /// dwell is what makes the loop's confidence achievable: `control_confidence`'s derivation shows a
    /// single-reading branch would need 34 standard errors — over four hours of history — where three
    /// consecutive readings need 2.5 and 89 seconds.
    ///
    /// It used to count `Verdict::Systemic` from `diagnose`, which agrees with the homeostat only on the
    /// over-coupled side: `diagnose` has no verdict for `Aggregate` or for a coherence collapse, and that is
    /// exactly why the other two branches had no dwell to gate them.
    fn advance_band_dwell(&mut self, band: Option<&BandControl>) -> bool {
        let this_band = band.map(core::mem::discriminant);
        self.band_streak = match (this_band, self.last_band) {
            (Some(now), Some(before)) if now == before => self.band_streak.saturating_add(1),
            (Some(_), _) => 1,
            (None, _) => 0,
        };
        self.last_band = this_band;
        self.band_streak >= BAND_DWELL
    }

    /// The correlation the shed is **actually reducing** — the cell's own measured mean off-diagonal
    /// correlation once it has a self-model, and the configured `healthy` baseline only until then (#92).
    ///
    /// The shed answers a *measured* over-coupling; scaling a configured constant instead meant the
    /// controller's model of what it had done bore no relation to what it was responding to. It also made
    /// every cap look arbitrary: at `healthy = 0.45` the whole budget down to the floor is 0.042, while an
    /// over-coupled cell is by definition above `hi = 0.577` and has four times that to give back.
    pub(crate) fn baseline_correlation(&self, healthy: f64) -> f64 {
        self.measured_correlation.unwrap_or(healthy)
    }

    /// This node's **effective** equicorrelated correlation: [`baseline_correlation`](Self::baseline_correlation)
    /// scaled down by the current `decoupling` shed factor (audit C6). Everything that computes `Φ`/`P` from
    /// a scalar correlation reads this, so a `Decouple` genuinely lowers the cell's integration.
    pub(crate) fn effective_correlation(&self, healthy: f64) -> f64 {
        self.baseline_correlation(healthy) * (1.0 - self.decoupling)
    }

    /// Assemble the live `7×7` polar cross-attestation matrix (spec §6.4) for `diagnose`'s structural
    /// check: for each polar point `k`, the 3 rates in its class default to this node's own honest reading
    /// of `degraded` (`polar::mediator_attestation` — always internally consistent, for ANY liveness
    /// pattern), then are overridden by `k`'s own freshly-gossiped `DiagAttest`, if any (fresh within
    /// `timeout`) — the mediator is the authoritative witness of the channels it mediates. An honest
    /// override reproduces the same self-consistent triple; an equivocating one's disagrees internally by
    /// construction — and `polar::violated_classes` then localizes exactly that mediator, since each class
    /// here is filled atomically from ONE source (fallback or attestation), never a mix.
    pub(crate) fn attested_pairwise_rates<F: Field>(
        &self,
        now: Instant,
        degraded: u8,
        timeout: Duration,
    ) -> ([[f64; 7]; 7], u8) {
        let mut matrix = [[0.0f64; 7]; 7];
        // **Which classes carry a real attestation** (#230). A class filled by the fallback is
        // `polar::mediator_attestation`, which is internally consistent for ANY liveness pattern by
        // construction — so it cannot violate, and a matrix assembled entirely from it cannot fire the
        // localizer at all. Measured over every one of the 256 `degraded` masks: **0 violations**, against
        // 1 for the same matrix with a single forged pair. The verdict "no Byzantine member" was therefore
        // carrying no information about how much evidence stood behind it.
        let mut attested_mask = 0u8;
        for k in 0..7usize {
            let coord = self.cell_coord::<F>(k);
            let triple = match self.attested.get(&coord) {
                Some((rates, seen)) if now.since(*seen) <= timeout => {
                    attested_mask |= 1u8 << k;
                    *rates
                }
                _ => polar::mediator_attestation(k, degraded),
            };
            for ((a, b), rate) in polar::polar_class(k).into_iter().zip(triple) {
                // `a`, `b` are Fano point indices (< 7) by construction of `polar_class`; `.get_mut`
                // avoids raw bracket indexing rather than asserting that invariant with an allow.
                if let Some(cell) = matrix.get_mut(a).and_then(|row| row.get_mut(b)) {
                    *cell = rate;
                }
                if let Some(cell) = matrix.get_mut(b).and_then(|row| row.get_mut(a)) {
                    *cell = rate;
                }
            }
        }
        (matrix, attested_mask)
    }

    /// Fold this window's cell health into a `CoherenceFrame`, record it in local history, and return the
    /// effect that publishes its wire bytes. The exact 3-bit syndrome comes from `degraded`; the coherence
    /// scalars from the equicorrelated liveness model at the *effective* (post-shed) correlation
    /// (docs/design-telemetry.md §2). `epoch` is the cell's AGREED epoch, so cross-node roll-up buckets
    /// consistently (audit A3).
    pub(crate) fn emit_observation(
        &mut self,
        now: Instant,
        epoch: Epoch,
        alive_count: usize,
        degraded: u8,
        healthy_correlation: f64,
    ) -> Effect {
        // **Report the matrix when there is one** (#226). The path below synthesises an equicorrelated
        // matrix from a single scalar, and an equicorrelated matrix has `dispersion ≡ 0` and a flat
        // diagonal BY CONSTRUCTION — so every second-dimension quantity in every production frame was
        // structurally zero, however uneven the real cell was. Measured on a 4-of-7 clique: the real fold
        // reads `0.13061224`, the synthesised one `1.31e-8`. Ten million to one.
        //
        // The frame's own `dispersion()` doc says a zero reading and a high one "want opposite operator
        // responses"; only one of the two was reachable, so the operator's second dimension was not merely
        // unread — it was unrepresentable.
        //
        // A measured frame reports the window it observed, with every scalar from one moment. It does NOT
        // fold in the post-shed `effective_correlation`: that is a *counterfactual* about the window to
        // come, it lives in [`counterfactual_phi`](Self::counterfactual_phi) where the healing budget reads
        // it, and mixing the two would put two moments in one frame. A `Decouple` therefore shows in the
        // frame one window later — which is correct, because one window is the instrument's resolution.
        if let Some(matrix) = self.monitor.ready().then(|| self.monitor.coherence()).flatten() {
            let frame = self.observer.observe_measured(
                now.as_nanos(),
                epoch.get(),
                &matrix,
                degraded,
                polar_gap_from_liveness(degraded),
                -1,
            );
            return Effect::Notify(Notification::Observed(frame.encode().to_vec()));
        }
        let correlation = self.effective_correlation(healthy_correlation);
        // **Say which of the two it is** (#154). `effective_correlation` falls back to the configured
        // `healthy_correlation` until a full window exists, and at the shipped `0.45` that fallback produces
        // a frame reading healthy on every axis from a node that has observed nothing. Since #153 clears the
        // window at every epoch boundary, that is ~89 s in every 600 rather than a startup transient, so the
        // distinction has to travel with the frame.
        let measured = self.measured_correlation.is_some();
        let frame = self.observer.observe_liveness(
            now.as_nanos(),
            epoch.get(),
            alive_count,
            correlation,
            measured,
            degraded,
            polar_gap_from_liveness(degraded), // spectral gap Δ (T-226(v)) from this window's health topology
            -1,                                // cascade forecast: none from liveness alone
        );
        Effect::Notify(Notification::Observed(frame.encode().to_vec()))
    }

    /// Publish this node's admission price here, at the operator's `floor`.
    ///
    /// Called once, when a proof-of-work gate is installed. Without it the controller runs on nothing and the
    /// price never moves — which is the correct behaviour for a node that charges no entry fee.
    pub(crate) fn set_admission(&mut self, floor: u32, live: LiveDifficulty) {
        self.admission_floor = floor;
        self.live_difficulty = Some(live);
    }

    /// Measure what an epoch advance costs this cell, and keep it.
    ///
    /// The one input to the epoch-cadence bound (`regeneration::min_epoch_period`) that cannot be read from a
    /// single window: `τ` comes from the line rates and `r_stab` from the purity, but `e₀` — the headroom an
    /// advance consumes — only exists as a *difference across the boundary*. So it is taken there: the
    /// stability radius entering an epoch, minus the radius on the first window of the next one.
    ///
    /// A negative difference is recorded as zero, not as a negative cost: a cell that came out of a reshuffle
    /// healthier than it went in was recovering from something else, and crediting the advance for it would let
    /// the floor drift below what the cell can actually sustain.
    fn measure_epoch_cost(&mut self, now: Instant, epoch: Epoch, purity: f64, n: usize, gap: f64) {
        let radius = stability::stability_radius(purity, n);
        self.latest = Some((radius, gap));
        // The observation cadence, measured rather than assumed: it is what converts a relaxation time in
        // master-equation steps into one in seconds.
        if let Some((_, then)) = self.last_purity {
            let elapsed = now.as_nanos().saturating_sub(then);
            if elapsed > 0 {
                #[allow(clippy::cast_precision_loss)] // a window is milliseconds; f64 holds it exactly
                let seconds = elapsed as f64 / 1e9;
                self.window_seconds = Some(seconds);
            }
        }
        match self.last_epoch {
            Some((seen, before)) if seen != epoch.get() => {
                self.epoch_cost = Some((before - radius).max(0.0));
                self.last_epoch = Some((epoch.get(), radius));
            }
            None => self.last_epoch = Some((epoch.get(), radius)),
            // Same epoch: keep the radius we entered it with, not this window's — the cost is measured against
            // the state the advance acted on.
            Some(_) => {}
        }
    }

    /// The shortest epoch period this cell can sustain, **in seconds**, from its own measurements.
    ///
    /// `None` until an advance has been observed *and* the observation cadence has been measured. Two of the
    /// three inputs to the bound come free from any window; the third — what an advance costs — is a difference
    /// across the epoch boundary, and a floor computed with a guessed one would read as derived and be
    /// invented.
    ///
    /// The conversion is not incidental. `Δ` counts corroborated-alive points per Fano line, so it carries no
    /// unit and `τ = 1/Δ` is a relaxation time in *observation windows*; seconds appear only by multiplying
    /// through by the measured window. A healthy cell has `Δ = 2`, and reporting its `τ = 0.5` as a wall-clock
    /// figure would have called half a step half a second.
    /// Force the measured stress — tests only.
    #[cfg(test)]
    pub(crate) fn set_stress_for_test(&mut self, stress: f64) {
        self.last_stress = stress;
    }

    /// What this node is carrying, per role, in `Role::ALL` order — `None` where it has no sensor.
    ///
    /// **Relay** is the count of frames this node **originated** since the last behavioural sample — read from
    /// the coherence self-slot, which counts originations, not forwarding. This doc used to call it "relays
    /// carried", which is the *other* counter (`activity`, keyed by peer) and would have sent the next
    /// maintainer to swap in the wrong quantity. Originations are the right one and not by luck: the setpoint
    /// asks how many relays the cell needs, so the load is the traffic that must be *carried*, summed once at
    /// the origin. Summing frames forwarded would count each frame once per hop and make the demand a function
    /// of the supply already deployed — a loop closed on itself.
    ///
    /// **Storage** is the number of keys this node holds shards for. Both are `Some`, *including when they read
    /// zero* — an idle relay measured no demand, and that is a reading. Service, exit and rendezvous are
    /// `None`: this function has no sensor for them, and the driver substitutes the node's own offer, because a
    /// fabricated demand of zero would retire a role on sight.
    ///
    /// The `Option` is the whole point and it is load-bearing. This returned a bare `[u16; 5]` and said in prose
    /// that a measured count and an offered one "would be unsafe to present as the same kind of number" — while
    /// making them the same `u16`, so the driver had to guess, and guessed *by value*: any zero became the
    /// offer. That silently discarded the true reading of a role that legitimately fell idle, which is precisely
    /// the moment the controller should shrink it, and it bound the two roles that **are** measured. A cell
    /// could not conclude "nobody here needs relays". Making absence a distinct inhabitant of the type is what
    /// lets the driver believe a `Some(0)` and substitute only on `None`.
    ///
    /// The width is [`Role::COUNT`], not a literal, so this fails to compile if a sixth role is added without
    /// widening the contract — which also pins the `5` in `Notification::LoadReport`, a crate that cannot see
    /// [`Role`] and so cannot state the relationship itself.
    ///
    /// The other three are **fed by the caller**, through [`load_effect`](Self::load_effect)'s reading argument:
    /// a composite engine reports the rendezvous registrations and the service intros it is carrying, and a
    /// driver gauge reports exit flows in flight. This function stays deliberately ignorant of all three — it
    /// knows what it counts and passes the rest through, so a new sensor needs no change here.
    fn load_report(&self, sensed: RoleReading) -> [Option<u16>; Role::COUNT] {
        // The contract crate cannot see `fanos-core`, so `Notification::LoadReport`'s width is a literal
        // there. This is where the two meet, so this is where they are proven equal — a sixth role that
        // updated one and not the other would otherwise truncate every reading in silence.
        const _: () = assert!(
            fanos_ports::ROLE_COUNT == Role::COUNT,
            "the load-report width and the role count must agree",
        );
        // The caller supplies every reading it can see; the healer fills in the one only it counts.
        sensed.measuring(Role::Relay, u16::try_from(self.self_activity).unwrap_or(u16::MAX)).into_array()
    }

    /// The stress this cell last measured, for a law that must decide outside the observation loop.
    pub(crate) fn stress(&self) -> f64 {
        self.last_stress
    }

    /// Take the epoch floor **if an advance has just been measured**, clearing the flag.
    ///
    /// Reported per advance rather than per window: the figure only changes when an advance is measured, and a
    /// value repeated every window would be noise an operator learns to ignore.
    fn take_epoch_floor(&mut self, epoch: Epoch) -> Option<f64> {
        if self.reported_epoch == Some(epoch.get()) || self.epoch_cost.is_none() {
            return None;
        }
        let floor = self.epoch_floor_seconds()?;
        self.reported_epoch = Some(epoch.get());
        Some(floor)
    }

    pub(crate) fn epoch_floor_seconds(&self) -> Option<f64> {
        let cost = self.epoch_cost?;
        let (radius, gap) = self.latest?;
        let window = self.window_seconds?;
        let tau_windows = if gap > 0.0 { 1.0 / gap } else { f64::INFINITY };
        Some(regeneration::min_epoch_period(tau_windows, cost, radius) * window)
    }

    /// What this node is carrying, as an effect — emitted every observation, coherence or not.
    ///
    /// `sensed` carries the readings the *caller* can see; the healer adds the one it counts itself (relay
    /// activity). Passing a reading rather than a bare shard count is what lets a composite engine — which owns
    /// the mix router, the rendezvous gatherer and the service line — fill in the three roles the overlay alone
    /// has no sensor for, without the healer growing a dependency on any of them.
    pub(crate) fn load_effect(&self, sensed: RoleReading) -> Effect {
        Effect::Notify(Notification::LoadReport { per_role: self.load_report(sensed) })
    }

    /// Run the per-observation control laws that need the cell's **coherence matrix**.
    ///
    /// Separate from the load report, which does not: a node knows how many keys it holds and how many relays
    /// it carried whether or not `Γ_net` has enough samples to exist yet. Folding the two together made the
    /// role controller's only real input wait on a quantity it never needed — caught by a test that asked a
    /// fresh node what it was carrying and got nothing.
    ///
    /// Grouped because they share one shape — each reads the cell's own state this window and either acts on it
    /// or tells someone who can. Kept out of `diagnose`, which is the *diagnosis*: sensing a fault and healing
    /// it is a different job from governing a price, a cadence, or a role.
    fn control_laws(
        &mut self,
        now: Instant,
        epoch: Epoch,
        purity: f64,
        n: usize,
        degraded: u8,
    ) -> Vec<Effect> {
        let gap = polar_gap_from_liveness(degraded);
        self.price_admission(now, purity, n, gap);
        self.measure_epoch_cost(now, epoch, purity, n, gap);
        let mut out = Vec::new();
        if let Some(seconds) = self.take_epoch_floor(epoch) {
            // A finite floor becomes milliseconds; an infinite one is the absent value, because "no
            // sustainable cadence" is not a very large period.
            #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
            let millis = seconds.is_finite().then(|| (seconds * 1000.0).max(0.0) as u64);
            out.push(Effect::Notify(Notification::EpochFloor { millis }));
        }
        out
    }

    /// Move this node's admission price to what its own measured stress justifies.
    ///
    /// The **actuator** of DDoS homeostasis. T-104 says a cell survives sustained noise iff `‖h‖ < κ·r_stab`,
    /// and every other response — the homeostat's band control, the healing plan's reroute and repair — acts on
    /// `κ` and on internal structure. This is the only one that acts on `‖h‖`, by making entry cost more.
    ///
    /// Everything it needs is already sensed or known: the purity and `N` from the measured `Γ_net`, the
    /// regeneration rate from the homeostat's own gain, and the baseline dissipation from this window's
    /// liveness topology. The one thing it must remember is the previous purity, because the disturbance is
    /// inferred from the *rate*, not the level.
    ///
    /// A node with no proof-of-work admission has no price to move, so this is inert there rather than
    /// pretending — and the controller can only ever raise the operator's floor, never open a door the
    /// operator closed.
    fn price_admission(&mut self, now: Instant, purity: f64, n: usize, lambda: f64) {
        let Some(live) = self.live_difficulty.clone() else { return };
        let nanos = now.as_nanos();
        let Some((previous, then)) = self.last_purity.replace((purity, nanos)) else {
            return; // the first window has no rate; a controller cannot act on one sample
        };
        let elapsed = nanos.saturating_sub(then);
        if elapsed == 0 {
            return;
        }
        #[allow(clippy::cast_precision_loss)] // a window is milliseconds; f64 holds it exactly
        let seconds = elapsed as f64 / 1e9;
        let kappa = self.homeostat.gain();
        let rate = (purity - previous) / seconds;
        let disturbance =
            inferred_disturbance(purity, rate, lambda, kappa, stability::p_opt(n), n);
        let stress = stability::stress(stability::stability_radius(purity, n), kappa, disturbance);
        self.last_stress = stress;
        // The window is the retention unit: the excursion decays as `(1 − κ·Δt)` over it, and releasing the
        // price faster than the cell recovers is precisely what makes the controller oscillate.
        let retention = 1.0 - (kappa * seconds).clamp(0.0, 1.0);
        live.set(self.admission.observe(self.admission_floor, stress, retention));
    }

    /// Φ at the correlation a prior shed leaves behind, holding **this cell's measured diagonal** fixed.
    ///
    /// **Counterfactual on purpose.** The exact `measures().phi` is not what the healing budget wants: the
    /// measured matrix is a window of past observations and cannot yet show what a `Decouple` just did.
    /// What it wants is Φ at the *effective* (post-shed) correlation, so that a prior shed has genuinely
    /// lowered it (audit C6).
    ///
    /// **At the measured diagonal, not a flat one** (UHM T-312/T-314). The general law is
    /// `Φ = r²(1−p)/p`; the closed form this replaced was `(alive−1)·r²`, its `p = 1/N` case. On a
    /// concentrated cell — one node relaying for the rest, which is the ordinary shape of a busy cell, not
    /// a pathology — that over-reports Φ. It gates a healing budget, so the error direction was "believe
    /// the cell is more integrated than it is".
    ///
    /// With no measured matrix there is no diagonal to hold, and flat is the only assumption available.
    /// `1 / alive_count` says that out loud rather than hiding it inside a closed form whose name mentions
    /// only the *correlation* stratum and not the diagonal one.
    fn counterfactual_phi(
        &self,
        healthy_correlation: f64,
        measured: Option<&fanos_diakrisis::CoherenceMatrix>,
        alive_count: usize,
    ) -> f64 {
        let p = measured.map_or_else(
            || 1.0 / f64::from(u32::try_from(alive_count.max(1)).unwrap_or(u32::MAX)),
            fanos_diakrisis::CoherenceMatrix::diagonal_purity,
        );
        phi_at(self.effective_correlation(healthy_correlation), p)
    }

    /// The polar cross-attestation matrix, plus a count of the live members that did **not** attest.
    ///
    /// **The matrix is always handed over, and the first version of this withheld it — which the
    /// equivocation scenario refuted immediately** (#230). Withholding on incomplete coverage took
    /// `0 of 6` honest observers where `6 of 6` had localized the equivocator: one quiet honest member
    /// disabled detection of a Byzantine one that HAD attested. The reason is that a class filled by the
    /// fallback is *inert*, not misleading — it cannot violate, so it cannot create a false positive, and
    /// dropping the whole matrix throws away the real evidence sitting beside it.
    ///
    /// So coverage qualifies the NEGATIVE, never the positive. A violation found is valid whatever else the
    /// matrix contains; "no violation found" is a claim only when every live member reported. Measured over
    /// all 256 `degraded` masks, a matrix built entirely from the fallback fires zero times
    /// (`polar::a_matrix_built_only_from_the_fallback_can_never_violate`), so an all-fallback "clean"
    /// verdict carried no evidence at all — and until the verdict can say so, the shortfall is at least
    /// counted here.
    ///
    /// A member attests every heartbeat unconditionally (`liveness::heartbeat`), so silence from a LIVE one
    /// is a refusal to be checked rather than missing data. One record per silent member, because "how many
    /// refused" is actionable and "how many windows were skipped" is not.
    fn attested_with_coverage<F: Field>(
        &self,
        now: Instant,
        degraded: u8,
        timeout: Duration,
        stations: &mut crate::ports::stations::Stations,
    ) -> [[f64; 7]; 7] {
        let (rates, attested_mask) = self.attested_pairwise_rates::<F>(now, degraded, timeout);
        let unattested = !degraded & 0x7F & !attested_mask;
        for _ in 0..unattested.count_ones() {
            stations.record(crate::ports::stations::Station::StructuralCheckUnattested, None);
        }
        rates
    }


    /// Diagnose the sensed cell snapshot (`self_index, degraded, alive_count`, produced by the facade's
    /// liveness sensing) and actuate any healing — the DIAKRISIS reflex proper. Feeds the *measured*
    /// behavioural `Γ_net` (the #74 unification) plus the live polar cross-attestation into `diagnose`,
    /// runs the verdict→plan→actuate path (over-coupling gated by the [`BAND_DWELL`] hysteresis, #122),
    /// then the homeostat's re-integration/escalation bands, and finally the mandatory self-observation.
    #[allow(clippy::too_many_arguments)] // the sensed cell snapshot: index, degraded, alive, lines, config, epoch
    pub(crate) fn diagnose<F: Field>(
        &mut self,
        now: Instant,
        self_index: usize,
        degraded: u8,
        alive_count: usize,
        healthy_lines: Option<u8>,
        responsive: Option<u8>,
        config: &Config,
        epoch: Epoch,
        stations: &mut crate::ports::stations::Stations,
    ) -> Vec<Effect> {
        // The base node senses liveness, and — the #74 unification — the *measured* behavioural coherence
        // `Γ_net` (the relay-activity self-model). Feeding `Γ_net` into `diagnose` makes its Systemic
        // (over-coupling) verdict fire on the same signal the homeostat acts on, so there is one
        // over-coupling authority, not a dormant liveness-only arm beside a separate behavioural check.
        // (Partition/cascade still need the global cross-attestation view, not this local sense alone.)
        // **Only from a full window.** `coherence()` yields a matrix as soon as every node has *two*
        // samples, and a two-point Pearson correlation is `±1` exactly — two points always lie on a line. A
        // freshly-started node would therefore read `Φ = 6` (every `|C_ij| = 1`) on its second heartbeat and
        // hand the homeostat a verdict of `Decouple` or `Bind` drawn from a matrix that carries no
        // information at all, before it has observed anything. `ready()` is the predicate written for exactly
        // this — *"the point at which the coherence read is stable"* — and until now nothing called it, so
        // the guard existed and was not installed. Below a full window the node has no self-model, which is
        // the honest state: `diagnose` keeps its liveness-only arm and the homeostat is not consulted.
        let measured = self.monitor.ready().then(|| self.monitor.coherence()).flatten();
        // **The band verdict, computed once.** It gates the dwell, supplies the shed, and dispatches the
        // re-integration/escalation arms below — three readers that used to call `control` twice with
        // identical arguments and derive the third from a different signal entirely.
        let band = measured.as_ref().map(|coherence| {
            let m = coherence.measures();
            self.homeostat.control(
                m.purity,
                coherence.mean_correlation(),
                coherence.diagonal_purity(),
                coherence.n(),
            )
        });
        // What the shed is reducing, kept for the laws that run outside this diagnosis (#92).
        self.measured_correlation =
            measured.as_ref().map(fanos_diakrisis::CoherenceMatrix::mean_correlation);
        // The structural (Byzantine) check (spec §6.4 + §6.2): the live polar cross-attestation matrix,
        // assembled from gossiped `DiagAttest` reports (§98). `diagnose` runs the 14 free polar sum-rules
        // against it FIRST, ahead of the syndrome localizer — an equivocating mediator's own report is
        // internally inconsistent and is caught and localized here; an honest cell's is always consistent,
        // so this never pre-empts the ordinary crash/churn path below, however many members are down.
        let pairwise_rates =
            Some(self.attested_with_coverage::<F>(now, degraded, config.liveness_timeout, stations));
        // §6.5 partition sensor (V14): `healthy_lines` names which cell lines carry live inter-node
        // connectivity, derived from the *measured* per-channel loss (the #106 grey substrate) — an
        // INDEPENDENT signal, not the node-liveness `degraded` mask (that would be redundant with the crash
        // path). Persistence guard: a disconnected loss-weighted graph is only trusted after
        // [`PARTITION_DWELL`] consecutive readings, so a recovery-loss transient (a just-healed node whose
        // lines still read cut for a round) never false-fires; below the dwell we present the cell as fully
        // connected so no premature `Verdict::Partition` escapes. Partition-resistance (one lossy line still
        // reads λ₂=4) means only a sustained lossy line-COVER — a real incipient split, nodes still alive —
        // ever reaches the verdict.
        // A partition candidate is only meaningful while the **endpoints survive**: a disconnection explained
        // by a node that is simply gone is a crash, the node-fault path owns it, and letting it build the
        // streak would false-fire on a crash+recovery transient.
        //
        // `degraded == 0` was the approximation, and it was too strong in exactly the direction that mattered.
        // It also excluded the case this sensor exists for — an incipient **lossy** cut, where a node is not
        // reachable enough to route through and is still plainly answering. Deriving the corroboration quorum
        // (#107) pushed such nodes over the degradation bar, and from that day the streak could never
        // accumulate on a real soft split. `responsive` restores it without a threshold: every degraded point
        // is still being heard from, so it is the graph that failed. When nothing is degraded this is
        // trivially true, so the old condition is a special case of the new one.
        let endpoints_survive = responsive.is_some_and(|r| degraded & !r == 0);
        let disconnected =
            endpoints_survive && healthy_lines.is_some_and(|h| !partition::is_connected(h));
        self.partition_streak = if disconnected {
            self.partition_streak.saturating_add(1)
        } else {
            0
        };
        let trusted_lines = match healthy_lines {
            Some(_) if disconnected && self.partition_streak < PARTITION_DWELL => Some(0x7F),
            other => other,
        };
        let verdict = diagnose(&Observation {
            degraded,
            pairwise_rates,
            coherence: measured.clone(),
            healthy_lines: trusted_lines,
            responsive,
        });

        let band_ready = self.advance_band_dwell(band.as_ref());

        let mut effects = alloc::vec![Effect::Notify(Notification::Verdict(verdict.clone()))];
        if config.self_healing {
            let phi = self.counterfactual_phi(config.healthy_correlation, measured.as_ref(), alive_count);
            self.last_phi = phi; // exposed to the facade's parent-stratum reflex (R-C2)
            let plan = plan_healing(&verdict, self_index, degraded, phi);
            if !plan.is_empty() {
                self.observer.note_healing();
            }
            // Over-coupling actuation (`Decouple`) flows through this verdict→plan path, gated by the dwell
            // hysteresis above; `apply_healing_plan` raises the mutable decoupling state and dedups the
            // notification (audit C6/#122). Crash/Byzantine actions in the plan are never gated.
            let decouple_ready = band_ready && matches!(band, Some(BandControl::Decouple { .. }));
            // **The shed comes from the homeostat, which is where the law is.** `control` returns a
            // `Decouple { effort }` proportional to the over-excursion; every other band contributes no
            // shed. Read from the one band verdict computed above, so the effort actuates in the round it
            // was computed for rather than the next one — the two paths used to be a round apart *and* the
            // effort was thrown away entirely (#91).
            let shed = match band {
                Some(BandControl::Decouple { effort }) => effort,
                _ => 0.0,
            };
            effects.extend(self.apply_healing_plan::<F>(
                now,
                &plan,
                decouple_ready,
                shed,
                alive_count,
                config.healthy_correlation,
            ));

            // The homeostat covers the bands the Systemic verdict does not: **re-integration** once the
            // measured `Γ_net` is back in (or below) the band (Bind/Hold — decay the shed), and
            // **escalation** on a coherence *collapse* (`P ≤ 2/N`). Over-coupling is the verdict path's.
            if let (Some(coherence), Some(band)) = (measured, band) {
                let m = coherence.measures();
                effects.extend(self.control_laws(now, epoch, m.purity, coherence.n(), degraded));
                match band {
                    BandControl::Escalate => {
                        // Gated by the same dwell as every other branch (#100): a collapse read once is a
                        // reading, read three times running it is a state. The latch dedups repeats *within*
                        // a collapse; the dwell is what stops the loop entering one on noise.
                        if band_ready && !self.escalated_coherence {
                            self.escalated_coherence = true;
                            self.observer.note_healing();
                            effects.push(Effect::Notify(Notification::Escalated(Escalation::CoherenceCollapse)));
                        }
                    }
                    BandControl::Decouple { .. } => {
                        // Actuated via the verdict→plan path above, which now reads this same control's
                        // `effort` before acting (#91) — so the law and the actuation are one decision
                        // rather than two that disagreed. Only the escalation latch is cleared here.
                        self.escalated_coherence = false;
                    }
                    band @ (BandControl::Bind { .. } | BandControl::Hold) => {
                        // In or below the band: let any prior shedding decay back toward the baseline
                        // coupling, and notify `Bound` once when fully re-integrated.
                        self.decoupling *= DECOUPLE_DECAY;
                        if self.decoupling < 1e-9 {
                            self.decoupling = 0.0;
                        }
                        self.escalated_coherence = false;
                        if self.decoupled && self.decoupling == 0.0 {
                            self.decoupled = false;
                            effects.push(Effect::Notify(Notification::Bound));
                        }
                        // §6.7 differential-DDoS response: the under-coupled `Bind` (`Aggregate`) band is the
                        // regime a load hotspot induces by decorrelating the cell. Publish the projective load
                        // state the node sensed — its per-point relay load over the whole cell (observable
                        // because its q+1 lines cover the plane) — once on ENTERING the band (deduped). The
                        // derived response is `loadbalance::balance_exact(loads)` = the uniform mean, driving
                        // the hotspot into the whole cell at the projective contraction `λ₂ = 2/9`. `Hold` is
                        // the healthy in-band collective subject: clear the latch so a later Bind re-publishes.
                        //
                        // Dwell-gated like the other two branches. `Bind` is the *noisier* side of the band —
                        // the floor sits closer to a healthy cell's operating point than the ceiling does —
                        // and it used to be the one branch that fired on a single reading, publishing a
                        // cell-wide rebalance from one sample of a statistic whose error spans the band.
                        if band_ready && matches!(band, BandControl::Bind { .. }) {
                            if !self.rebalancing {
                                self.rebalancing = true;
                                let loads = self.last_sample.map(|x| x.round() as u32);
                                effects.push(Effect::Notify(Notification::Rebalance { loads }));
                            }
                        } else {
                            self.rebalancing = false;
                        }
                    }
                }
            }
        }
        // Mandatory self-observation: diagnosis cannot happen without observing.
        effects.push(self.emit_observation(
            now,
            epoch,
            alive_count,
            degraded,
            config.healthy_correlation,
        ));
        effects
    }

    /// Apply a [`HealingPlan`], mutating the reroute / repaired / quarantine state and emitting a
    /// notification for each *new* corrective action (idempotent across repeated rounds).
    /// `shed` is the homeostat's proportional effort for this round and `(alive, healthy)` the cell size and
    /// baseline correlation the shed ceiling is derived from — see the `Decouple` arm.
    pub(crate) fn apply_healing_plan<F: Field>(
        &mut self,
        now: Instant,
        plan: &fanos_diakrisis::HealingPlan,
        decouple_ready: bool,
        shed: f64,
        alive: usize,
        healthy: f64,
    ) -> Vec<Effect> {
        let mut effects = Vec::new();
        for action in &plan.actions {
            match *action {
                HealingAction::Reroute { around, via } => {
                    let around_c = self.cell_coord::<F>(around);
                    let via_c = self.cell_coord::<F>(via);
                    if self.reroute.insert(around_c, via_c) != Some(via_c) {
                        effects.push(Effect::Notify(Notification::Rerouted {
                            around: around_c,
                            via: via_c,
                        }));
                    }
                }
                HealingAction::Repair { node, .. } => {
                    let node_c = self.cell_coord::<F>(node);
                    if self.repaired.insert(node_c) {
                        effects.push(Effect::Notify(Notification::Repaired(node_c)));
                    }
                }
                HealingAction::Quarantine { node } => {
                    let node_c = self.cell_coord::<F>(node);
                    effects.extend(self.quarantine(node_c, now));
                }
                HealingAction::Decouple => {
                    // Real correlation-shedding (audit C6), gated by the dwell hysteresis (#122): only once
                    // over-coupling has held for BAND_DWELL consecutive diagnoses do we raise the
                    // mutable decoupling factor, lowering the effective correlation feeding `Φ` next round.
                    // Notify once on *entering* the shed regime (dedup), not each round.
                    //
                    // **The step is the homeostat's own proportional law, not a constant (#91).**
                    // `Homeostat::control` computes `effort = κ(r − hi)/hi` — gradient descent on
                    // `V = ‖Γ − ρ*‖²`, which is what makes the closed loop inherit the T-104 contraction —
                    // and this actuator used to discard it and add a fixed 0.25. That was wrong by a factor
                    // of three for the shipped cell: one such step modelled `r` at 0.3375 against a
                    // collective-subject floor of 0.4082, so a single over-coupling response flipped the
                    // cell's self-model into the *under*-coupled band, whose answer is `Bind`.
                    if decouple_ready {
                        let ceiling =
                            decouple_ceiling(alive, self.baseline_correlation(healthy), self.behavior_window, self.control_confidence);
                        self.decoupling = (self.decoupling + shed).min(ceiling);
                        if !self.decoupled {
                            self.decoupled = true;
                            effects.push(Effect::Notify(Notification::Decoupled));
                        }
                    }
                }
                HealingAction::Escalate { unrecoverable } => {
                    effects.push(Effect::Notify(Notification::Escalated(Escalation::Faults(unrecoverable))));
                }
            }
        }
        effects
    }

    /// Locally quarantine `node_c` (spec §6.2/§6.4): drop its frames for the bounded re-admission window,
    /// emitting a `Quarantined` notification only on a *new* distrust (idempotent across rounds). The single
    /// quarantine actuator shared by the mediator model (`violated_classes`, via the healing plan) and the
    /// endpoint fabrication detector ([`attest_endpoints`]) — one reason for a member's frames to be dropped.
    /// Clear any quarantine tag on `node_c`, re-admitting it immediately rather than at TTL expiry.
    ///
    /// Used when a coordinate's **occupant changes** (audit R-M1): a tag belongs to an identity, and the arriving
    /// identity has not earned its predecessor's distrust. Silent — re-admission is the absence of a verdict, not a
    /// verdict, so it emits no notification.
    pub(crate) fn readmit(&mut self, node_c: Triple) {
        self.quarantined.remove(&node_c);
    }

    pub(crate) fn quarantine(&mut self, node_c: Triple, now: Instant) -> Option<Effect> {
        self.quarantined
            .insert(node_c, now)
            .is_none()
            .then_some(Effect::Notify(Notification::Quarantined(node_c)))
    }

    /// The **§6.4 endpoint cross-attestation, live** (#106). Fold this heartbeat's per-witness liveness
    /// fresh-masks (built by the facade from the corroborated `witnessed` substrate) into the bounded window
    /// and, once it is full, run the directional fabrication detector: quarantine any witness that
    /// *persistently* vouches a node fresh while a firm consensus reports it stale — a colluding
    /// vouch-fabricator keeping a dead node believed-alive, the fault the plain corroboration quorum (which
    /// only counts vouchers) is defeated by. `subjects` are the points the judge cannot itself directly
    /// confirm alive (`!own_fresh_mask`), so a node it can see is never adjudicated — the honest-node
    /// safeguard. Dual to the quorum; complements the mediator model's equivocation catch. Below a full
    /// window there is not enough history to judge persistence, so nothing fires (churn-safe cold start).
    pub(crate) fn attest_endpoints<F: Field>(
        &mut self,
        now: Instant,
        round: [Option<u8>; 7],
        subjects: u8,
    ) -> Vec<Effect> {
        self.endpoint_window.push_back(round);
        while self.endpoint_window.len() > ENDPOINT_WINDOW {
            self.endpoint_window.pop_front();
        }
        if self.endpoint_window.len() < ENDPOINT_WINDOW {
            return Vec::new();
        }
        let window: Vec<[Option<u8>; 7]> = self.endpoint_window.iter().copied().collect();
        let mut effects = Vec::new();
        for idx in polar::fabricators_by_persistent_freshness(&window, ENDPOINT_MIN_STALE, subjects)
        {
            let node_c = self.cell_coord::<F>(idx);
            effects.extend(self.quarantine(node_c, now));
        }
        effects
    }
}

